generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LaboratorioFabricante
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          laboratorio_fabricante
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        pais_id:        {label: 'País de Origen'}
        ciudad_id:      {label: 'Ciudad de Origen'}
        pais:           {label: 'País de Origen'}
        bajo_liciencia: {label: 'Bajo Licencia de'}
        direccion:      {label: 'Dirección'}
        telefono:       {label: 'Teléfono'}
        email:          {label: 'E-mail'}
        list_pais:      {label: 'País'} 
      list: 
        title: Listado de Laboratorios Farmaceuticos Registrados
        max_per_page: 15
        display: [nombre, list_pais, telefono]
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter:
        display:        [nombre, pais_id] 
      form:
        display:        [pais_id, ciudad_id, nombre, bajo_licencia, para, direccion, telefono, fax, email, observaciones]
      edit:    
        title: Editar Laboratorio %%nombre%%
      new:
        title: Registro de Laboratorios Farmaceuticos
