<?php

/**
 * BaseMedicamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $producto_id
 * @property integer $empresa_id
 * @property integer $laboratorio_fabricante_id
 * @property integer $forma_farmaceutica_id
 * @property integer $via_administracion_id
 * @property integer $tipo_venta_id
 * @property integer $formula_cc_id
 * @property string $nombre_comercial
 * @property string $nombre_generico
 * @property string $concentracion
 * @property string $accion_terapeutica
 * @property string $conservacion
 * @property string $periodo_validez
 * @property string $especificacion_envase
 * @property string $envase_clinico
 * @property string $aval
 * @property string $registro_sanitario
 * @property string $certificado_control
 * @property string $descripcion
 * @property Doctrine_Collection $Formulario5
 * @property Producto $Producto
 * @property Empresa $Empresa
 * @property LaboratorioFabricante $LaboratorioFabricante
 * @property FormaFarmaceutica $FormaFarmaceutica
 * @property ViaAdministracion $ViaAdministracion
 * @property TipoVenta $TipoVenta
 * @property FormulaCc $FormulaCc
 * 
 * @method integer               getProductoId()                Returns the current record's "producto_id" value
 * @method integer               getEmpresaId()                 Returns the current record's "empresa_id" value
 * @method integer               getLaboratorioFabricanteId()   Returns the current record's "laboratorio_fabricante_id" value
 * @method integer               getFormaFarmaceuticaId()       Returns the current record's "forma_farmaceutica_id" value
 * @method integer               getViaAdministracionId()       Returns the current record's "via_administracion_id" value
 * @method integer               getTipoVentaId()               Returns the current record's "tipo_venta_id" value
 * @method integer               getFormulaCcId()               Returns the current record's "formula_cc_id" value
 * @method string                getNombreComercial()           Returns the current record's "nombre_comercial" value
 * @method string                getNombreGenerico()            Returns the current record's "nombre_generico" value
 * @method string                getConcentracion()             Returns the current record's "concentracion" value
 * @method string                getAccionTerapeutica()         Returns the current record's "accion_terapeutica" value
 * @method string                getConservacion()              Returns the current record's "conservacion" value
 * @method string                getPeriodoValidez()            Returns the current record's "periodo_validez" value
 * @method string                getEspecificacionEnvase()      Returns the current record's "especificacion_envase" value
 * @method string                getEnvaseClinico()             Returns the current record's "envase_clinico" value
 * @method string                getAval()                      Returns the current record's "aval" value
 * @method string                getRegistroSanitario()         Returns the current record's "registro_sanitario" value
 * @method string                getCertificadoControl()        Returns the current record's "certificado_control" value
 * @method string                getDescripcion()               Returns the current record's "descripcion" value
 * @method Doctrine_Collection   getFormulario5()               Returns the current record's "Formulario5" collection
 * @method Producto              getProducto()                  Returns the current record's "Producto" value
 * @method Empresa               getEmpresa()                   Returns the current record's "Empresa" value
 * @method LaboratorioFabricante getLaboratorioFabricante()     Returns the current record's "LaboratorioFabricante" value
 * @method FormaFarmaceutica     getFormaFarmaceutica()         Returns the current record's "FormaFarmaceutica" value
 * @method ViaAdministracion     getViaAdministracion()         Returns the current record's "ViaAdministracion" value
 * @method TipoVenta             getTipoVenta()                 Returns the current record's "TipoVenta" value
 * @method FormulaCc             getFormulaCc()                 Returns the current record's "FormulaCc" value
 * @method Medicamento           setProductoId()                Sets the current record's "producto_id" value
 * @method Medicamento           setEmpresaId()                 Sets the current record's "empresa_id" value
 * @method Medicamento           setLaboratorioFabricanteId()   Sets the current record's "laboratorio_fabricante_id" value
 * @method Medicamento           setFormaFarmaceuticaId()       Sets the current record's "forma_farmaceutica_id" value
 * @method Medicamento           setViaAdministracionId()       Sets the current record's "via_administracion_id" value
 * @method Medicamento           setTipoVentaId()               Sets the current record's "tipo_venta_id" value
 * @method Medicamento           setFormulaCcId()               Sets the current record's "formula_cc_id" value
 * @method Medicamento           setNombreComercial()           Sets the current record's "nombre_comercial" value
 * @method Medicamento           setNombreGenerico()            Sets the current record's "nombre_generico" value
 * @method Medicamento           setConcentracion()             Sets the current record's "concentracion" value
 * @method Medicamento           setAccionTerapeutica()         Sets the current record's "accion_terapeutica" value
 * @method Medicamento           setConservacion()              Sets the current record's "conservacion" value
 * @method Medicamento           setPeriodoValidez()            Sets the current record's "periodo_validez" value
 * @method Medicamento           setEspecificacionEnvase()      Sets the current record's "especificacion_envase" value
 * @method Medicamento           setEnvaseClinico()             Sets the current record's "envase_clinico" value
 * @method Medicamento           setAval()                      Sets the current record's "aval" value
 * @method Medicamento           setRegistroSanitario()         Sets the current record's "registro_sanitario" value
 * @method Medicamento           setCertificadoControl()        Sets the current record's "certificado_control" value
 * @method Medicamento           setDescripcion()               Sets the current record's "descripcion" value
 * @method Medicamento           setFormulario5()               Sets the current record's "Formulario5" collection
 * @method Medicamento           setProducto()                  Sets the current record's "Producto" value
 * @method Medicamento           setEmpresa()                   Sets the current record's "Empresa" value
 * @method Medicamento           setLaboratorioFabricante()     Sets the current record's "LaboratorioFabricante" value
 * @method Medicamento           setFormaFarmaceutica()         Sets the current record's "FormaFarmaceutica" value
 * @method Medicamento           setViaAdministracion()         Sets the current record's "ViaAdministracion" value
 * @method Medicamento           setTipoVenta()                 Sets the current record's "TipoVenta" value
 * @method Medicamento           setFormulaCc()                 Sets the current record's "FormulaCc" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedicamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('medicamento');
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('laboratorio_fabricante_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('forma_farmaceutica_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('via_administracion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tipo_venta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('formula_cc_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('nombre_comercial', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nombre_generico', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('concentracion', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('accion_terapeutica', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('conservacion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('periodo_validez', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('especificacion_envase', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('envase_clinico', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('aval', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('registro_sanitario', 'string', 50, array(
             'type' => 'string',
             'unique' => false,
             'length' => 50,
             ));
        $this->hasColumn('certificado_control', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('descripcion', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Formulario5', array(
             'local' => 'id',
             'foreign' => 'medicamento_id'));

        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('LaboratorioFabricante', array(
             'local' => 'laboratorio_fabricante_id',
             'foreign' => 'id'));

        $this->hasOne('FormaFarmaceutica', array(
             'local' => 'forma_farmaceutica_id',
             'foreign' => 'id'));

        $this->hasOne('ViaAdministracion', array(
             'local' => 'via_administracion_id',
             'foreign' => 'id'));

        $this->hasOne('TipoVenta', array(
             'local' => 'tipo_venta_id',
             'foreign' => 'id'));

        $this->hasOne('FormulaCc', array(
             'local' => 'formula_cc_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}