<?php

/**
 * BaseCiudad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pais_id
 * @property string $nombre
 * @property Pais $Pais
 * @property Doctrine_Collection $Empresas
 * @property LaboratorioFabricante $LaboratorioFabricante
 * @property Doctrine_Collection $Formularios706
 * 
 * @method integer               getPaisId()                Returns the current record's "pais_id" value
 * @method string                getNombre()                Returns the current record's "nombre" value
 * @method Pais                  getPais()                  Returns the current record's "Pais" value
 * @method Doctrine_Collection   getEmpresas()              Returns the current record's "Empresas" collection
 * @method LaboratorioFabricante getLaboratorioFabricante() Returns the current record's "LaboratorioFabricante" value
 * @method Doctrine_Collection   getFormularios706()        Returns the current record's "Formularios706" collection
 * @method Ciudad                setPaisId()                Sets the current record's "pais_id" value
 * @method Ciudad                setNombre()                Sets the current record's "nombre" value
 * @method Ciudad                setPais()                  Sets the current record's "Pais" value
 * @method Ciudad                setEmpresas()              Sets the current record's "Empresas" collection
 * @method Ciudad                setLaboratorioFabricante() Sets the current record's "LaboratorioFabricante" value
 * @method Ciudad                setFormularios706()        Sets the current record's "Formularios706" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCiudad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ciudad');
        $this->hasColumn('pais_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pais', array(
             'local' => 'pais_id',
             'foreign' => 'id'));

        $this->hasMany('Empresa as Empresas', array(
             'local' => 'id',
             'foreign' => 'ciudad_id'));

        $this->hasOne('LaboratorioFabricante', array(
             'local' => 'id',
             'foreign' => 'ciudad_id'));

        $this->hasMany('Formulario706 as Formularios706', array(
             'local' => 'id',
             'foreign' => 'rescom_ciudad_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}