<?php

/**
 * BaseEtapa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $formulario_id
 * @property integer $tipo_etapa_id
 * @property string $descripcion
 * @property string $observacion
 * @property date $fecha_fin
 * @property TipoEtapa $TipoEtapa
 * @property Formulario $Formulario
 * @property Doctrine_Collection $Validacion
 * 
 * @method integer             getFormularioId()  Returns the current record's "formulario_id" value
 * @method integer             getTipoEtapaId()   Returns the current record's "tipo_etapa_id" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method string              getObservacion()   Returns the current record's "observacion" value
 * @method date                getFechaFin()      Returns the current record's "fecha_fin" value
 * @method TipoEtapa           getTipoEtapa()     Returns the current record's "TipoEtapa" value
 * @method Formulario          getFormulario()    Returns the current record's "Formulario" value
 * @method Doctrine_Collection getValidacion()    Returns the current record's "Validacion" collection
 * @method Etapa               setFormularioId()  Sets the current record's "formulario_id" value
 * @method Etapa               setTipoEtapaId()   Sets the current record's "tipo_etapa_id" value
 * @method Etapa               setDescripcion()   Sets the current record's "descripcion" value
 * @method Etapa               setObservacion()   Sets the current record's "observacion" value
 * @method Etapa               setFechaFin()      Sets the current record's "fecha_fin" value
 * @method Etapa               setTipoEtapa()     Sets the current record's "TipoEtapa" value
 * @method Etapa               setFormulario()    Sets the current record's "Formulario" value
 * @method Etapa               setValidacion()    Sets the current record's "Validacion" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEtapa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('etapa');
        $this->hasColumn('formulario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_etapa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('observacion', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('fecha_fin', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoEtapa', array(
             'local' => 'tipo_etapa_id',
             'foreign' => 'id'));

        $this->hasOne('Formulario', array(
             'local' => 'formulario_id',
             'foreign' => 'id'));

        $this->hasMany('ValidacionEtapa as Validacion', array(
             'local' => 'tipo_etapa_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}