<?php

/**
 * BaseTipoCalificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Formulario11 $Formulario11
 * @property Doctrine_Collection $Formulario7
 * 
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method Formulario11        getFormulario11() Returns the current record's "Formulario11" value
 * @method Doctrine_Collection getFormulario7()  Returns the current record's "Formulario7" collection
 * @method TipoCalificacion    setNombre()       Sets the current record's "nombre" value
 * @method TipoCalificacion    setFormulario11() Sets the current record's "Formulario11" value
 * @method TipoCalificacion    setFormulario7()  Sets the current record's "Formulario7" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoCalificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_calificacion');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario11', array(
             'local' => 'id',
             'foreign' => 'tipo_calificacion_id'));

        $this->hasMany('Formulario7', array(
             'local' => 'id',
             'foreign' => 'tipo_calificacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}