<?php

/**
 * BaseEmisionCorrespondencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tipo_documento_id
 * @property integer $empresa_id
 * @property string $otro_destino
 * @property integer $emisor_id
 * @property string $factura
 * @property date $factura_fecha
 * @property string $monto_item
 * @property string $nombre
 * @property string $numero
 * @property integer $codigo_producto_id
 * @property integer $forma_cosmetica_id
 * @property date $fecha_inicio_vigencia
 * @property string $vigencia
 * @property date $fecha_envio
 * @property string $numero_guia
 * @property TipoDocumento $TipoDocumento
 * @property Empresa $Empresa
 * @property Emisor $Emisor
 * @property FormaCosmetica $FormaCosmetica
 * @property CodigoProducto $CodigoProducto
 * 
 * @method integer                getTipoDocumentoId()       Returns the current record's "tipo_documento_id" value
 * @method integer                getEmpresaId()             Returns the current record's "empresa_id" value
 * @method string                 getOtroDestino()           Returns the current record's "otro_destino" value
 * @method integer                getEmisorId()              Returns the current record's "emisor_id" value
 * @method string                 getFactura()               Returns the current record's "factura" value
 * @method date                   getFacturaFecha()          Returns the current record's "factura_fecha" value
 * @method string                 getMontoItem()             Returns the current record's "monto_item" value
 * @method string                 getNombre()                Returns the current record's "nombre" value
 * @method string                 getNumero()                Returns the current record's "numero" value
 * @method integer                getCodigoProductoId()      Returns the current record's "codigo_producto_id" value
 * @method integer                getFormaCosmeticaId()      Returns the current record's "forma_cosmetica_id" value
 * @method date                   getFechaInicioVigencia()   Returns the current record's "fecha_inicio_vigencia" value
 * @method string                 getVigencia()              Returns the current record's "vigencia" value
 * @method date                   getFechaEnvio()            Returns the current record's "fecha_envio" value
 * @method string                 getNumeroGuia()            Returns the current record's "numero_guia" value
 * @method TipoDocumento          getTipoDocumento()         Returns the current record's "TipoDocumento" value
 * @method Empresa                getEmpresa()               Returns the current record's "Empresa" value
 * @method Emisor                 getEmisor()                Returns the current record's "Emisor" value
 * @method FormaCosmetica         getFormaCosmetica()        Returns the current record's "FormaCosmetica" value
 * @method CodigoProducto         getCodigoProducto()        Returns the current record's "CodigoProducto" value
 * @method EmisionCorrespondencia setTipoDocumentoId()       Sets the current record's "tipo_documento_id" value
 * @method EmisionCorrespondencia setEmpresaId()             Sets the current record's "empresa_id" value
 * @method EmisionCorrespondencia setOtroDestino()           Sets the current record's "otro_destino" value
 * @method EmisionCorrespondencia setEmisorId()              Sets the current record's "emisor_id" value
 * @method EmisionCorrespondencia setFactura()               Sets the current record's "factura" value
 * @method EmisionCorrespondencia setFacturaFecha()          Sets the current record's "factura_fecha" value
 * @method EmisionCorrespondencia setMontoItem()             Sets the current record's "monto_item" value
 * @method EmisionCorrespondencia setNombre()                Sets the current record's "nombre" value
 * @method EmisionCorrespondencia setNumero()                Sets the current record's "numero" value
 * @method EmisionCorrespondencia setCodigoProductoId()      Sets the current record's "codigo_producto_id" value
 * @method EmisionCorrespondencia setFormaCosmeticaId()      Sets the current record's "forma_cosmetica_id" value
 * @method EmisionCorrespondencia setFechaInicioVigencia()   Sets the current record's "fecha_inicio_vigencia" value
 * @method EmisionCorrespondencia setVigencia()              Sets the current record's "vigencia" value
 * @method EmisionCorrespondencia setFechaEnvio()            Sets the current record's "fecha_envio" value
 * @method EmisionCorrespondencia setNumeroGuia()            Sets the current record's "numero_guia" value
 * @method EmisionCorrespondencia setTipoDocumento()         Sets the current record's "TipoDocumento" value
 * @method EmisionCorrespondencia setEmpresa()               Sets the current record's "Empresa" value
 * @method EmisionCorrespondencia setEmisor()                Sets the current record's "Emisor" value
 * @method EmisionCorrespondencia setFormaCosmetica()        Sets the current record's "FormaCosmetica" value
 * @method EmisionCorrespondencia setCodigoProducto()        Sets the current record's "CodigoProducto" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmisionCorrespondencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emision_correspondencia');
        $this->hasColumn('tipo_documento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('otro_destino', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('emisor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('factura', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('factura_fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('monto_item', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('nombre', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('numero', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('codigo_producto_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('forma_cosmetica_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha_inicio_vigencia', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('vigencia', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('fecha_envio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('numero_guia', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoDocumento', array(
             'local' => 'tipo_documento_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('Emisor', array(
             'local' => 'emisor_id',
             'foreign' => 'id'));

        $this->hasOne('FormaCosmetica', array(
             'local' => 'forma_cosmetica_id',
             'foreign' => 'id'));

        $this->hasOne('CodigoProducto', array(
             'local' => 'codigo_producto_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}