<?php

/**
 * BaseCalificacionServicio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $Satisfaccion
 * 
 * @method string               getNombre()       Returns the current record's "nombre" value
 * @method Doctrine_Collection  getSatisfaccion() Returns the current record's "Satisfaccion" collection
 * @method CalificacionServicio setNombre()       Sets the current record's "nombre" value
 * @method CalificacionServicio setSatisfaccion() Sets the current record's "Satisfaccion" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalificacionServicio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('calificacion_servicio');
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Satisfaccion', array(
             'local' => 'id',
             'foreign' => 'calificacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}