<?php

/**
 * BaseViaAdministracion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $Medicamento
 * @property Doctrine_Collection $Formulario7
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method Doctrine_Collection getMedicamento() Returns the current record's "Medicamento" collection
 * @method Doctrine_Collection getFormulario7() Returns the current record's "Formulario7" collection
 * @method ViaAdministracion   setNombre()      Sets the current record's "nombre" value
 * @method ViaAdministracion   setMedicamento() Sets the current record's "Medicamento" collection
 * @method ViaAdministracion   setFormulario7() Sets the current record's "Formulario7" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseViaAdministracion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('via_administracion');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Medicamento', array(
             'local' => 'id',
             'foreign' => 'via_administracion_id'));

        $this->hasMany('Formulario7', array(
             'local' => 'id',
             'foreign' => 'via_administracion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}