<?php

/**
 * BaseFormulario12
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $formulario_id
 * @property date $fecha
 * @property integer $vigencia
 * @property date $fecha_inicio_vigencia
 * @property integer $numero_ruta
 * @property integer $reactivo_id
 * @property integer $tipo_tramite_formulario12_id
 * @property integer $origen_formulario_id
 * @property string $modificacion
 * @property Formulario $Formulario
 * @property Reactivo $Reactivo
 * @property TipoTramiteFormulario12 $TipoTramiteFormulario12
 * @property OrigenFormulario $OrigenFormulario
 * 
 * @method integer                 getFormularioId()                 Returns the current record's "formulario_id" value
 * @method date                    getFecha()                        Returns the current record's "fecha" value
 * @method integer                 getVigencia()                     Returns the current record's "vigencia" value
 * @method date                    getFechaInicioVigencia()          Returns the current record's "fecha_inicio_vigencia" value
 * @method integer                 getNumeroRuta()                   Returns the current record's "numero_ruta" value
 * @method integer                 getReactivoId()                   Returns the current record's "reactivo_id" value
 * @method integer                 getTipoTramiteFormulario12Id()    Returns the current record's "tipo_tramite_formulario12_id" value
 * @method integer                 getOrigenFormularioId()           Returns the current record's "origen_formulario_id" value
 * @method string                  getModificacion()                 Returns the current record's "modificacion" value
 * @method Formulario              getFormulario()                   Returns the current record's "Formulario" value
 * @method Reactivo                getReactivo()                     Returns the current record's "Reactivo" value
 * @method TipoTramiteFormulario12 getTipoTramiteFormulario12()      Returns the current record's "TipoTramiteFormulario12" value
 * @method OrigenFormulario        getOrigenFormulario()             Returns the current record's "OrigenFormulario" value
 * @method Formulario12            setFormularioId()                 Sets the current record's "formulario_id" value
 * @method Formulario12            setFecha()                        Sets the current record's "fecha" value
 * @method Formulario12            setVigencia()                     Sets the current record's "vigencia" value
 * @method Formulario12            setFechaInicioVigencia()          Sets the current record's "fecha_inicio_vigencia" value
 * @method Formulario12            setNumeroRuta()                   Sets the current record's "numero_ruta" value
 * @method Formulario12            setReactivoId()                   Sets the current record's "reactivo_id" value
 * @method Formulario12            setTipoTramiteFormulario12Id()    Sets the current record's "tipo_tramite_formulario12_id" value
 * @method Formulario12            setOrigenFormularioId()           Sets the current record's "origen_formulario_id" value
 * @method Formulario12            setModificacion()                 Sets the current record's "modificacion" value
 * @method Formulario12            setFormulario()                   Sets the current record's "Formulario" value
 * @method Formulario12            setReactivo()                     Sets the current record's "Reactivo" value
 * @method Formulario12            setTipoTramiteFormulario12()      Sets the current record's "TipoTramiteFormulario12" value
 * @method Formulario12            setOrigenFormulario()             Sets the current record's "OrigenFormulario" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormulario12 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formulario12');
        $this->hasColumn('formulario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('vigencia', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('fecha_inicio_vigencia', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('numero_ruta', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('reactivo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_tramite_formulario12_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('origen_formulario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('modificacion', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario', array(
             'local' => 'formulario_id',
             'foreign' => 'id'));

        $this->hasOne('Reactivo', array(
             'local' => 'reactivo_id',
             'foreign' => 'id'));

        $this->hasOne('TipoTramiteFormulario12', array(
             'local' => 'tipo_tramite_formulario12_id',
             'foreign' => 'id'));

        $this->hasOne('OrigenFormulario', array(
             'local' => 'origen_formulario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}