<?php

/**
 * BaseIniciacionFormulario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $empresa_id
 * @property integer $etapa_id
 * @property string $tramite
 * @property string $descripcion
 * @property string $observacion
 * @property date $fecha_fin
 * @property Empresa $Empresa
 * @property Etapa $Etapa
 * 
 * @method integer              getEmpresaId()   Returns the current record's "empresa_id" value
 * @method integer              getEtapaId()     Returns the current record's "etapa_id" value
 * @method string               getTramite()     Returns the current record's "tramite" value
 * @method string               getDescripcion() Returns the current record's "descripcion" value
 * @method string               getObservacion() Returns the current record's "observacion" value
 * @method date                 getFechaFin()    Returns the current record's "fecha_fin" value
 * @method Empresa              getEmpresa()     Returns the current record's "Empresa" value
 * @method Etapa                getEtapa()       Returns the current record's "Etapa" value
 * @method IniciacionFormulario setEmpresaId()   Sets the current record's "empresa_id" value
 * @method IniciacionFormulario setEtapaId()     Sets the current record's "etapa_id" value
 * @method IniciacionFormulario setTramite()     Sets the current record's "tramite" value
 * @method IniciacionFormulario setDescripcion() Sets the current record's "descripcion" value
 * @method IniciacionFormulario setObservacion() Sets the current record's "observacion" value
 * @method IniciacionFormulario setFechaFin()    Sets the current record's "fecha_fin" value
 * @method IniciacionFormulario setEmpresa()     Sets the current record's "Empresa" value
 * @method IniciacionFormulario setEtapa()       Sets the current record's "Etapa" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIniciacionFormulario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('iniciacion_formulario');
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('etapa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tramite', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('descripcion', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('observacion', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('fecha_fin', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('Etapa', array(
             'local' => 'etapa_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}