<?php

/**
 * BaseTipoTramiteFormulario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Formulario516 $Formulario516
 * @property Doctrine_Collection $Formulario706
 * 
 * @method string                getNombre()        Returns the current record's "nombre" value
 * @method Formulario516         getFormulario516() Returns the current record's "Formulario516" value
 * @method Doctrine_Collection   getFormulario706() Returns the current record's "Formulario706" collection
 * @method TipoTramiteFormulario setNombre()        Sets the current record's "nombre" value
 * @method TipoTramiteFormulario setFormulario516() Sets the current record's "Formulario516" value
 * @method TipoTramiteFormulario setFormulario706() Sets the current record's "Formulario706" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoTramiteFormulario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_tramite_formulario');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario516', array(
             'local' => 'id',
             'foreign' => 'tipo_tramite_formulario_id'));

        $this->hasMany('Formulario706', array(
             'local' => 'id',
             'foreign' => 'tipo_tramite_formulario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}