<?php

/**
 * BaseProductoUnimed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_producto_id
 * @property integer $numero_registro
 * @property date $fecha_registro
 * @property string $notificacion
 * @property string $nombre_comercial
 * @property string $nombre_generico
 * @property string $forma_farmaceutica
 * @property string $concentracion
 * @property string $laboratorio_fabricante
 * @property string $pais_origen
 * @property CodigoProducto $CodigoProducto
 * 
 * @method integer        getCodigoProductoId()       Returns the current record's "codigo_producto_id" value
 * @method integer        getNumeroRegistro()         Returns the current record's "numero_registro" value
 * @method date           getFechaRegistro()          Returns the current record's "fecha_registro" value
 * @method string         getNotificacion()           Returns the current record's "notificacion" value
 * @method string         getNombreComercial()        Returns the current record's "nombre_comercial" value
 * @method string         getNombreGenerico()         Returns the current record's "nombre_generico" value
 * @method string         getFormaFarmaceutica()      Returns the current record's "forma_farmaceutica" value
 * @method string         getConcentracion()          Returns the current record's "concentracion" value
 * @method string         getLaboratorioFabricante()  Returns the current record's "laboratorio_fabricante" value
 * @method string         getPaisOrigen()             Returns the current record's "pais_origen" value
 * @method CodigoProducto getCodigoProducto()         Returns the current record's "CodigoProducto" value
 * @method ProductoUnimed setCodigoProductoId()       Sets the current record's "codigo_producto_id" value
 * @method ProductoUnimed setNumeroRegistro()         Sets the current record's "numero_registro" value
 * @method ProductoUnimed setFechaRegistro()          Sets the current record's "fecha_registro" value
 * @method ProductoUnimed setNotificacion()           Sets the current record's "notificacion" value
 * @method ProductoUnimed setNombreComercial()        Sets the current record's "nombre_comercial" value
 * @method ProductoUnimed setNombreGenerico()         Sets the current record's "nombre_generico" value
 * @method ProductoUnimed setFormaFarmaceutica()      Sets the current record's "forma_farmaceutica" value
 * @method ProductoUnimed setConcentracion()          Sets the current record's "concentracion" value
 * @method ProductoUnimed setLaboratorioFabricante()  Sets the current record's "laboratorio_fabricante" value
 * @method ProductoUnimed setPaisOrigen()             Sets the current record's "pais_origen" value
 * @method ProductoUnimed setCodigoProducto()         Sets the current record's "CodigoProducto" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductoUnimed extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto_unimed');
        $this->hasColumn('codigo_producto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numero_registro', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_registro', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('notificacion', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('nombre_comercial', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nombre_generico', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('forma_farmaceutica', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('concentracion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('laboratorio_fabricante', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pais_origen', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CodigoProducto', array(
             'local' => 'codigo_producto_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}