<?php

/**
 * BaseCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $empresa_id
 * @property sfGuardUser $sfGuardUser
 * @property Empresa $Empresa
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getEmpresaId()   Returns the current record's "empresa_id" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Empresa     getEmpresa()     Returns the current record's "Empresa" value
 * @method Cliente     setUserId()      Sets the current record's "user_id" value
 * @method Cliente     setEmpresaId()   Sets the current record's "empresa_id" value
 * @method Cliente     setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Cliente     setEmpresa()     Sets the current record's "Empresa" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}