<?php

/**
 * BaseCodigoProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $EmisionCorrespondencia
 * @property Doctrine_Collection $Producto
 * @property Doctrine_Collection $ProductoUnimed
 * 
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method string              getDescripcion()            Returns the current record's "descripcion" value
 * @method Doctrine_Collection getEmisionCorrespondencia() Returns the current record's "EmisionCorrespondencia" collection
 * @method Doctrine_Collection getProducto()               Returns the current record's "Producto" collection
 * @method Doctrine_Collection getProductoUnimed()         Returns the current record's "ProductoUnimed" collection
 * @method CodigoProducto      setNombre()                 Sets the current record's "nombre" value
 * @method CodigoProducto      setDescripcion()            Sets the current record's "descripcion" value
 * @method CodigoProducto      setEmisionCorrespondencia() Sets the current record's "EmisionCorrespondencia" collection
 * @method CodigoProducto      setProducto()               Sets the current record's "Producto" collection
 * @method CodigoProducto      setProductoUnimed()         Sets the current record's "ProductoUnimed" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCodigoProducto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('codigo_producto');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('descripcion', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EmisionCorrespondencia', array(
             'local' => 'id',
             'foreign' => 'codigo_producto_id'));

        $this->hasMany('Producto', array(
             'local' => 'id',
             'foreign' => 'codigo_producto_id'));

        $this->hasMany('ProductoUnimed', array(
             'local' => 'id',
             'foreign' => 'codigo_producto_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}