<?php

/**
 * BaseProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $empresa_id
 * @property integer $laboratorio_fabricante_id
 * @property string $nombre_generico
 * @property string $descripcion
 * @property string $procedencia
 * @property string $registro_sanitario
 * @property Empresa $Empresa
 * @property LaboratorioFabricante $LaboratorioFabricante
 * @property Doctrine_Collection $Formulario5
 * @property Medicamento $Medicamento
 * @property DispositivoMedico $DispositivoMedico
 * @property Formulario27 $Formulario27
 * @property Doctrine_Collection $Cosmetico
 * @property Doctrine_Collection $Formulario516
 * @property Doctrine_Collection $Higiene
 * @property Doctrine_Collection $Formulario706
 * 
 * @method integer               getEmpresaId()                 Returns the current record's "empresa_id" value
 * @method integer               getLaboratorioFabricanteId()   Returns the current record's "laboratorio_fabricante_id" value
 * @method string                getNombreGenerico()            Returns the current record's "nombre_generico" value
 * @method string                getDescripcion()               Returns the current record's "descripcion" value
 * @method string                getProcedencia()               Returns the current record's "procedencia" value
 * @method string                getRegistroSanitario()         Returns the current record's "registro_sanitario" value
 * @method Empresa               getEmpresa()                   Returns the current record's "Empresa" value
 * @method LaboratorioFabricante getLaboratorioFabricante()     Returns the current record's "LaboratorioFabricante" value
 * @method Doctrine_Collection   getFormulario5()               Returns the current record's "Formulario5" collection
 * @method Medicamento           getMedicamento()               Returns the current record's "Medicamento" value
 * @method DispositivoMedico     getDispositivoMedico()         Returns the current record's "DispositivoMedico" value
 * @method Formulario27          getFormulario27()              Returns the current record's "Formulario27" value
 * @method Doctrine_Collection   getCosmetico()                 Returns the current record's "Cosmetico" collection
 * @method Doctrine_Collection   getFormulario516()             Returns the current record's "Formulario516" collection
 * @method Doctrine_Collection   getHigiene()                   Returns the current record's "Higiene" collection
 * @method Doctrine_Collection   getFormulario706()             Returns the current record's "Formulario706" collection
 * @method Producto              setEmpresaId()                 Sets the current record's "empresa_id" value
 * @method Producto              setLaboratorioFabricanteId()   Sets the current record's "laboratorio_fabricante_id" value
 * @method Producto              setNombreGenerico()            Sets the current record's "nombre_generico" value
 * @method Producto              setDescripcion()               Sets the current record's "descripcion" value
 * @method Producto              setProcedencia()               Sets the current record's "procedencia" value
 * @method Producto              setRegistroSanitario()         Sets the current record's "registro_sanitario" value
 * @method Producto              setEmpresa()                   Sets the current record's "Empresa" value
 * @method Producto              setLaboratorioFabricante()     Sets the current record's "LaboratorioFabricante" value
 * @method Producto              setFormulario5()               Sets the current record's "Formulario5" collection
 * @method Producto              setMedicamento()               Sets the current record's "Medicamento" value
 * @method Producto              setDispositivoMedico()         Sets the current record's "DispositivoMedico" value
 * @method Producto              setFormulario27()              Sets the current record's "Formulario27" value
 * @method Producto              setCosmetico()                 Sets the current record's "Cosmetico" collection
 * @method Producto              setFormulario516()             Sets the current record's "Formulario516" collection
 * @method Producto              setHigiene()                   Sets the current record's "Higiene" collection
 * @method Producto              setFormulario706()             Sets the current record's "Formulario706" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProducto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto');
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('laboratorio_fabricante_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre_generico', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('procedencia', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('registro_sanitario', 'string', 50, array(
             'type' => 'string',
             'unique' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('LaboratorioFabricante', array(
             'local' => 'laboratorio_fabricante_id',
             'foreign' => 'id'));

        $this->hasMany('Formulario5', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasOne('Medicamento', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasOne('DispositivoMedico', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasOne('Formulario27', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasMany('Cosmetico', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasMany('Formulario516', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasMany('Higiene', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasMany('Formulario706', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}