<?php

/**
 * BaseOrigenFormulario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Formulario5 $Formulario5
 * @property Formulario27 $Formulario27
 * @property Doctrine_Collection $Formulario12
 * 
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method Formulario5         getFormulario5()  Returns the current record's "Formulario5" value
 * @method Formulario27        getFormulario27() Returns the current record's "Formulario27" value
 * @method Doctrine_Collection getFormulario12() Returns the current record's "Formulario12" collection
 * @method OrigenFormulario    setNombre()       Sets the current record's "nombre" value
 * @method OrigenFormulario    setFormulario5()  Sets the current record's "Formulario5" value
 * @method OrigenFormulario    setFormulario27() Sets the current record's "Formulario27" value
 * @method OrigenFormulario    setFormulario12() Sets the current record's "Formulario12" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrigenFormulario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('origen_formulario');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario5', array(
             'local' => 'id',
             'foreign' => 'origen_formulario_id'));

        $this->hasOne('Formulario27', array(
             'local' => 'id',
             'foreign' => 'origen_formulario_id'));

        $this->hasMany('Formulario12', array(
             'local' => 'id',
             'foreign' => 'origen_formulario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}