<?php

/**
 * BaseDispositivoMedico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $producto_id
 * @property string $nombre_comercial
 * @property string $clasificacion_riesgo
 * @property string $codigo_internacional
 * @property boolean $manual
 * @property string $indicaciones
 * @property string $presentacion
 * @property string $condicion_empaque
 * @property string $vida_util
 * @property string $metodo_desecho
 * @property Producto $Producto
 * 
 * @method integer           getProductoId()           Returns the current record's "producto_id" value
 * @method string            getNombreComercial()      Returns the current record's "nombre_comercial" value
 * @method string            getClasificacionRiesgo()  Returns the current record's "clasificacion_riesgo" value
 * @method string            getCodigoInternacional()  Returns the current record's "codigo_internacional" value
 * @method boolean           getManual()               Returns the current record's "manual" value
 * @method string            getIndicaciones()         Returns the current record's "indicaciones" value
 * @method string            getPresentacion()         Returns the current record's "presentacion" value
 * @method string            getCondicionEmpaque()     Returns the current record's "condicion_empaque" value
 * @method string            getVidaUtil()             Returns the current record's "vida_util" value
 * @method string            getMetodoDesecho()        Returns the current record's "metodo_desecho" value
 * @method Producto          getProducto()             Returns the current record's "Producto" value
 * @method DispositivoMedico setProductoId()           Sets the current record's "producto_id" value
 * @method DispositivoMedico setNombreComercial()      Sets the current record's "nombre_comercial" value
 * @method DispositivoMedico setClasificacionRiesgo()  Sets the current record's "clasificacion_riesgo" value
 * @method DispositivoMedico setCodigoInternacional()  Sets the current record's "codigo_internacional" value
 * @method DispositivoMedico setManual()               Sets the current record's "manual" value
 * @method DispositivoMedico setIndicaciones()         Sets the current record's "indicaciones" value
 * @method DispositivoMedico setPresentacion()         Sets the current record's "presentacion" value
 * @method DispositivoMedico setCondicionEmpaque()     Sets the current record's "condicion_empaque" value
 * @method DispositivoMedico setVidaUtil()             Sets the current record's "vida_util" value
 * @method DispositivoMedico setMetodoDesecho()        Sets the current record's "metodo_desecho" value
 * @method DispositivoMedico setProducto()             Sets the current record's "Producto" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDispositivoMedico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dispositivo_medico');
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre_comercial', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('clasificacion_riesgo', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('codigo_internacional', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('manual', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('indicaciones', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('presentacion', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('condicion_empaque', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('vida_util', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('metodo_desecho', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}