<?php

/**
 * BaseFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property string $codigo
 * @property string $señores
 * @property integer $num_nit
 * @property Formulario11 $Formulario11
 * @property Doctrine_Collection $Item
 * 
 * @method date                getFecha()        Returns the current record's "fecha" value
 * @method string              getCodigo()       Returns the current record's "codigo" value
 * @method string              getSe()           Returns the current record's "se" value
 * @method integer             getNumNit()       Returns the current record's "num_nit" value
 * @method Formulario11        getFormulario11() Returns the current record's "Formulario11" value
 * @method Doctrine_Collection getItem()         Returns the current record's "Item" collection
 * @method Factura             setFecha()        Sets the current record's "fecha" value
 * @method Factura             setCodigo()       Sets the current record's "codigo" value
 * @method Factura             setSe()           Sets the current record's "se" value
 * @method Factura             setNumNit()       Sets the current record's "num_nit" value
 * @method Factura             setFormulario11() Sets the current record's "Formulario11" value
 * @method Factura             setItem()         Sets the current record's "Item" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFactura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('factura');
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('codigo', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('señores', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('num_nit', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario11', array(
             'local' => 'id',
             'foreign' => 'factura_id'));

        $this->hasMany('Item', array(
             'local' => 'id',
             'foreign' => 'factura_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}