<?php

/**
 * BaseRegenteFarmaceutico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $persona_id
 * @property string $matricula_profesional
 * @property string $carnet_colegiado
 * @property boolean $is_active
 * @property Persona $Persona
 * @property Empresa $Empresa
 * 
 * @method integer             getPersonaId()             Returns the current record's "persona_id" value
 * @method string              getMatriculaProfesional()  Returns the current record's "matricula_profesional" value
 * @method string              getCarnetColegiado()       Returns the current record's "carnet_colegiado" value
 * @method boolean             getIsActive()              Returns the current record's "is_active" value
 * @method Persona             getPersona()               Returns the current record's "Persona" value
 * @method Empresa             getEmpresa()               Returns the current record's "Empresa" value
 * @method RegenteFarmaceutico setPersonaId()             Sets the current record's "persona_id" value
 * @method RegenteFarmaceutico setMatriculaProfesional()  Sets the current record's "matricula_profesional" value
 * @method RegenteFarmaceutico setCarnetColegiado()       Sets the current record's "carnet_colegiado" value
 * @method RegenteFarmaceutico setIsActive()              Sets the current record's "is_active" value
 * @method RegenteFarmaceutico setPersona()               Sets the current record's "Persona" value
 * @method RegenteFarmaceutico setEmpresa()               Sets the current record's "Empresa" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegenteFarmaceutico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('regente_farmaceutico');
        $this->hasColumn('persona_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('matricula_profesional', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('carnet_colegiado', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'persona_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'id',
             'foreign' => 'regente_farmaceutico_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}