<?php

/**
 * BaseDatosFormulario27
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Formulario27 $Formulario27
 * 
 * @method string            getNombre()       Returns the current record's "nombre" value
 * @method Formulario27      getFormulario27() Returns the current record's "Formulario27" value
 * @method DatosFormulario27 setNombre()       Sets the current record's "nombre" value
 * @method DatosFormulario27 setFormulario27() Sets the current record's "Formulario27" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDatosFormulario27 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('datos_formulario27');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario27', array(
             'local' => 'id',
             'foreign' => 'datos_formulario27_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}