<?php

/**
 * BaseFormulaCc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $detalle_formula_cc_id
 * @property Doctrine_Collection $DetalleFormulaCc
 * 
 * @method integer             getDetalleFormulaCcId()    Returns the current record's "detalle_formula_cc_id" value
 * @method Doctrine_Collection getDetalleFormulaCc()      Returns the current record's "DetalleFormulaCc" collection
 * @method FormulaCc           setDetalleFormulaCcId()    Sets the current record's "detalle_formula_cc_id" value
 * @method FormulaCc           setDetalleFormulaCc()      Sets the current record's "DetalleFormulaCc" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormulaCc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formula_cc');
        $this->hasColumn('detalle_formula_cc_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DetalleFormulaCc', array(
             'local' => 'detalle_formula_cc_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}