<?php

/**
 * BaseTipoTramiteFormulario12
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Formulario12 $Formulario12
 * 
 * @method string                  getNombre()       Returns the current record's "nombre" value
 * @method Formulario12            getFormulario12() Returns the current record's "Formulario12" value
 * @method TipoTramiteFormulario12 setNombre()       Sets the current record's "nombre" value
 * @method TipoTramiteFormulario12 setFormulario12() Sets the current record's "Formulario12" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoTramiteFormulario12 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_tramite_formulario12');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario12', array(
             'local' => 'id',
             'foreign' => 'tipo_tramite_formulario12_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}