<?php

/**
 * BaseFormulario7
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $formulario_id
 * @property date $fecha
 * @property integer $vigencia
 * @property date $fecha_inicio_vigencia
 * @property string $referencia_aval
 * @property integer $producto_id
 * @property integer $tipo_calificacion_id
 * @property integer $via_administracion_id
 * @property string $accion_terapeutica
 * @property string $dosis
 * @property string $indicaciones
 * @property string $contraindicaciones
 * @property string $precauciones
 * @property string $efectos_secundarios
 * @property string $observaciones
 * @property string $comision
 * @property string $calificacion
 * @property Formulario $Formulario
 * @property Producto $Producto
 * @property TipoCalificacion $TipoCalificacion
 * @property ViaAdministracion $ViaAdministracion
 * 
 * @method integer           getFormularioId()          Returns the current record's "formulario_id" value
 * @method date              getFecha()                 Returns the current record's "fecha" value
 * @method integer           getVigencia()              Returns the current record's "vigencia" value
 * @method date              getFechaInicioVigencia()   Returns the current record's "fecha_inicio_vigencia" value
 * @method string            getReferenciaAval()        Returns the current record's "referencia_aval" value
 * @method integer           getProductoId()            Returns the current record's "producto_id" value
 * @method integer           getTipoCalificacionId()    Returns the current record's "tipo_calificacion_id" value
 * @method integer           getViaAdministracionId()   Returns the current record's "via_administracion_id" value
 * @method string            getAccionTerapeutica()     Returns the current record's "accion_terapeutica" value
 * @method string            getDosis()                 Returns the current record's "dosis" value
 * @method string            getIndicaciones()          Returns the current record's "indicaciones" value
 * @method string            getContraindicaciones()    Returns the current record's "contraindicaciones" value
 * @method string            getPrecauciones()          Returns the current record's "precauciones" value
 * @method string            getEfectosSecundarios()    Returns the current record's "efectos_secundarios" value
 * @method string            getObservaciones()         Returns the current record's "observaciones" value
 * @method string            getComision()              Returns the current record's "comision" value
 * @method string            getCalificacion()          Returns the current record's "calificacion" value
 * @method Formulario        getFormulario()            Returns the current record's "Formulario" value
 * @method Producto          getProducto()              Returns the current record's "Producto" value
 * @method TipoCalificacion  getTipoCalificacion()      Returns the current record's "TipoCalificacion" value
 * @method ViaAdministracion getViaAdministracion()     Returns the current record's "ViaAdministracion" value
 * @method Formulario7       setFormularioId()          Sets the current record's "formulario_id" value
 * @method Formulario7       setFecha()                 Sets the current record's "fecha" value
 * @method Formulario7       setVigencia()              Sets the current record's "vigencia" value
 * @method Formulario7       setFechaInicioVigencia()   Sets the current record's "fecha_inicio_vigencia" value
 * @method Formulario7       setReferenciaAval()        Sets the current record's "referencia_aval" value
 * @method Formulario7       setProductoId()            Sets the current record's "producto_id" value
 * @method Formulario7       setTipoCalificacionId()    Sets the current record's "tipo_calificacion_id" value
 * @method Formulario7       setViaAdministracionId()   Sets the current record's "via_administracion_id" value
 * @method Formulario7       setAccionTerapeutica()     Sets the current record's "accion_terapeutica" value
 * @method Formulario7       setDosis()                 Sets the current record's "dosis" value
 * @method Formulario7       setIndicaciones()          Sets the current record's "indicaciones" value
 * @method Formulario7       setContraindicaciones()    Sets the current record's "contraindicaciones" value
 * @method Formulario7       setPrecauciones()          Sets the current record's "precauciones" value
 * @method Formulario7       setEfectosSecundarios()    Sets the current record's "efectos_secundarios" value
 * @method Formulario7       setObservaciones()         Sets the current record's "observaciones" value
 * @method Formulario7       setComision()              Sets the current record's "comision" value
 * @method Formulario7       setCalificacion()          Sets the current record's "calificacion" value
 * @method Formulario7       setFormulario()            Sets the current record's "Formulario" value
 * @method Formulario7       setProducto()              Sets the current record's "Producto" value
 * @method Formulario7       setTipoCalificacion()      Sets the current record's "TipoCalificacion" value
 * @method Formulario7       setViaAdministracion()     Sets the current record's "ViaAdministracion" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormulario7 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formulario7');
        $this->hasColumn('formulario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('vigencia', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('fecha_inicio_vigencia', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('referencia_aval', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tipo_calificacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('via_administracion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('accion_terapeutica', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('dosis', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('indicaciones', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
        $this->hasColumn('contraindicaciones', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
        $this->hasColumn('precauciones', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
        $this->hasColumn('efectos_secundarios', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
        $this->hasColumn('observaciones', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('comision', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('calificacion', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario', array(
             'local' => 'formulario_id',
             'foreign' => 'id'));

        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasOne('TipoCalificacion', array(
             'local' => 'tipo_calificacion_id',
             'foreign' => 'id'));

        $this->hasOne('ViaAdministracion', array(
             'local' => 'via_administracion_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}