<?php

/**
 * BaseEtapa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $formulario5_id
 * @property integer $formulario27_id
 * @property integer $formulario516_id
 * @property integer $formulario706_id
 * @property integer $tipo_etapa_id
 * @property date $fecha
 * @property string $observacion
 * @property TipoEtapa $TipoEtapa
 * @property Formulario5 $Formulario5
 * @property Formulario27 $Formulario27
 * @property Formulario516 $Formulario516
 * @property Formulario706 $Formulario706
 * 
 * @method integer       getFormulario5Id()    Returns the current record's "formulario5_id" value
 * @method integer       getFormulario27Id()   Returns the current record's "formulario27_id" value
 * @method integer       getFormulario516Id()  Returns the current record's "formulario516_id" value
 * @method integer       getFormulario706Id()  Returns the current record's "formulario706_id" value
 * @method integer       getTipoEtapaId()      Returns the current record's "tipo_etapa_id" value
 * @method date          getFecha()            Returns the current record's "fecha" value
 * @method string        getObservacion()      Returns the current record's "observacion" value
 * @method TipoEtapa     getTipoEtapa()        Returns the current record's "TipoEtapa" value
 * @method Formulario5   getFormulario5()      Returns the current record's "Formulario5" value
 * @method Formulario27  getFormulario27()     Returns the current record's "Formulario27" value
 * @method Formulario516 getFormulario516()    Returns the current record's "Formulario516" value
 * @method Formulario706 getFormulario706()    Returns the current record's "Formulario706" value
 * @method Etapa         setFormulario5Id()    Sets the current record's "formulario5_id" value
 * @method Etapa         setFormulario27Id()   Sets the current record's "formulario27_id" value
 * @method Etapa         setFormulario516Id()  Sets the current record's "formulario516_id" value
 * @method Etapa         setFormulario706Id()  Sets the current record's "formulario706_id" value
 * @method Etapa         setTipoEtapaId()      Sets the current record's "tipo_etapa_id" value
 * @method Etapa         setFecha()            Sets the current record's "fecha" value
 * @method Etapa         setObservacion()      Sets the current record's "observacion" value
 * @method Etapa         setTipoEtapa()        Sets the current record's "TipoEtapa" value
 * @method Etapa         setFormulario5()      Sets the current record's "Formulario5" value
 * @method Etapa         setFormulario27()     Sets the current record's "Formulario27" value
 * @method Etapa         setFormulario516()    Sets the current record's "Formulario516" value
 * @method Etapa         setFormulario706()    Sets the current record's "Formulario706" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEtapa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('etapa');
        $this->hasColumn('formulario5_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('formulario27_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('formulario516_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('formulario706_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tipo_etapa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('observacion', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoEtapa', array(
             'local' => 'tipo_etapa_id',
             'foreign' => 'id'));

        $this->hasOne('Formulario5', array(
             'local' => 'formulario5_id',
             'foreign' => 'id'));

        $this->hasOne('Formulario27', array(
             'local' => 'formulario27_id',
             'foreign' => 'id'));

        $this->hasOne('Formulario516', array(
             'local' => 'formulario516_id',
             'foreign' => 'id'));

        $this->hasOne('Formulario706', array(
             'local' => 'formulario706_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}