<?php

/**
 * BaseFormulario27
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property integer $vigencia
 * @property date $fecha_inicio_vigencia
 * @property integer $numero_ruta
 * @property integer $tipo_tramite_formulario27_id
 * @property integer $origen_formulario_id
 * @property integer $datos_formulario27_id
 * @property integer $producto_id
 * @property Producto $Producto
 * @property TipoTramiteFormulario27 $TipoTramiteFormulario27
 * @property DatosFormulario27 $DatosFormulario27
 * @property OrigenFormulario $OrigenFormulario
 * @property Doctrine_Collection $Etapa
 * 
 * @method date                    getFecha()                        Returns the current record's "fecha" value
 * @method integer                 getVigencia()                     Returns the current record's "vigencia" value
 * @method date                    getFechaInicioVigencia()          Returns the current record's "fecha_inicio_vigencia" value
 * @method integer                 getNumeroRuta()                   Returns the current record's "numero_ruta" value
 * @method integer                 getTipoTramiteFormulario27Id()    Returns the current record's "tipo_tramite_formulario27_id" value
 * @method integer                 getOrigenFormularioId()           Returns the current record's "origen_formulario_id" value
 * @method integer                 getDatosFormulario27Id()          Returns the current record's "datos_formulario27_id" value
 * @method integer                 getProductoId()                   Returns the current record's "producto_id" value
 * @method Producto                getProducto()                     Returns the current record's "Producto" value
 * @method TipoTramiteFormulario27 getTipoTramiteFormulario27()      Returns the current record's "TipoTramiteFormulario27" value
 * @method DatosFormulario27       getDatosFormulario27()            Returns the current record's "DatosFormulario27" value
 * @method OrigenFormulario        getOrigenFormulario()             Returns the current record's "OrigenFormulario" value
 * @method Doctrine_Collection     getEtapa()                        Returns the current record's "Etapa" collection
 * @method Formulario27            setFecha()                        Sets the current record's "fecha" value
 * @method Formulario27            setVigencia()                     Sets the current record's "vigencia" value
 * @method Formulario27            setFechaInicioVigencia()          Sets the current record's "fecha_inicio_vigencia" value
 * @method Formulario27            setNumeroRuta()                   Sets the current record's "numero_ruta" value
 * @method Formulario27            setTipoTramiteFormulario27Id()    Sets the current record's "tipo_tramite_formulario27_id" value
 * @method Formulario27            setOrigenFormularioId()           Sets the current record's "origen_formulario_id" value
 * @method Formulario27            setDatosFormulario27Id()          Sets the current record's "datos_formulario27_id" value
 * @method Formulario27            setProductoId()                   Sets the current record's "producto_id" value
 * @method Formulario27            setProducto()                     Sets the current record's "Producto" value
 * @method Formulario27            setTipoTramiteFormulario27()      Sets the current record's "TipoTramiteFormulario27" value
 * @method Formulario27            setDatosFormulario27()            Sets the current record's "DatosFormulario27" value
 * @method Formulario27            setOrigenFormulario()             Sets the current record's "OrigenFormulario" value
 * @method Formulario27            setEtapa()                        Sets the current record's "Etapa" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormulario27 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formulario27');
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('vigencia', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('fecha_inicio_vigencia', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('numero_ruta', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tipo_tramite_formulario27_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('origen_formulario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('datos_formulario27_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasOne('TipoTramiteFormulario27', array(
             'local' => 'tipo_tramite_formulario27_id',
             'foreign' => 'id'));

        $this->hasOne('DatosFormulario27', array(
             'local' => 'datos_formulario27_id',
             'foreign' => 'id'));

        $this->hasOne('OrigenFormulario', array(
             'local' => 'origen_formulario_id',
             'foreign' => 'id'));

        $this->hasMany('Etapa', array(
             'local' => 'id',
             'foreign' => 'formulario27_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}