<?php

/**
 * BaseFormulario5
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property integer $tipo_tramite_formulario5_id
 * @property integer $tipo_producto_formulario5_id
 * @property integer $origen_formulario5_id
 * @property integer $producto_id
 * @property Producto $Producto
 * @property Doctrine_Collection $TipoTramite
 * @property Doctrine_Collection $TipoProducto
 * @property Doctrine_Collection $Origen
 * 
 * @method date                getFecha()                        Returns the current record's "fecha" value
 * @method integer             getTipoTramiteFormulario5Id()     Returns the current record's "tipo_tramite_formulario5_id" value
 * @method integer             getTipoProductoFormulario5Id()    Returns the current record's "tipo_producto_formulario5_id" value
 * @method integer             getOrigenFormulario5Id()          Returns the current record's "origen_formulario5_id" value
 * @method integer             getProductoId()                   Returns the current record's "producto_id" value
 * @method Producto            getProducto()                     Returns the current record's "Producto" value
 * @method Doctrine_Collection getTipoTramite()                  Returns the current record's "TipoTramite" collection
 * @method Doctrine_Collection getTipoProducto()                 Returns the current record's "TipoProducto" collection
 * @method Doctrine_Collection getOrigen()                       Returns the current record's "Origen" collection
 * @method Formulario5         setFecha()                        Sets the current record's "fecha" value
 * @method Formulario5         setTipoTramiteFormulario5Id()     Sets the current record's "tipo_tramite_formulario5_id" value
 * @method Formulario5         setTipoProductoFormulario5Id()    Sets the current record's "tipo_producto_formulario5_id" value
 * @method Formulario5         setOrigenFormulario5Id()          Sets the current record's "origen_formulario5_id" value
 * @method Formulario5         setProductoId()                   Sets the current record's "producto_id" value
 * @method Formulario5         setProducto()                     Sets the current record's "Producto" value
 * @method Formulario5         setTipoTramite()                  Sets the current record's "TipoTramite" collection
 * @method Formulario5         setTipoProducto()                 Sets the current record's "TipoProducto" collection
 * @method Formulario5         setOrigen()                       Sets the current record's "Origen" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormulario5 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formulario5');
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('tipo_tramite_formulario5_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_producto_formulario5_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('origen_formulario5_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasMany('TipoTramiteFormulario5 as TipoTramite', array(
             'local' => 'tipo_tramite_formulario5_id',
             'foreign' => 'id'));

        $this->hasMany('TipoProductoFormulario5 as TipoProducto', array(
             'local' => 'tipo_producto_formulario5_id',
             'foreign' => 'id'));

        $this->hasMany('OrigenFormulario5 as Origen', array(
             'local' => 'origen_formulario5_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}