<?php

/**
 * BaseTipoCalificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Formulario7 $Formulario7
 * @property Aval $Aval
 * 
 * @method string           getNombre()      Returns the current record's "nombre" value
 * @method Formulario7      getFormulario7() Returns the current record's "Formulario7" value
 * @method Aval             getAval()        Returns the current record's "Aval" value
 * @method TipoCalificacion setNombre()      Sets the current record's "nombre" value
 * @method TipoCalificacion setFormulario7() Sets the current record's "Formulario7" value
 * @method TipoCalificacion setAval()        Sets the current record's "Aval" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoCalificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_calificacion');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Formulario7', array(
             'local' => 'id',
             'foreign' => 'tipo_calificacion_id'));

        $this->hasOne('Aval', array(
             'local' => 'id',
             'foreign' => 'tipo_calificacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}