<?php

/**
 * BaseGrupoHigiene
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $Higiene
 * 
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method Doctrine_Collection getHigienes() Returns the current record's "Higienes" collection
 * @method Doctrine_Collection getHigiene()  Returns the current record's "Higiene" collection
 * @method GrupoHigiene        setNombre()   Sets the current record's "nombre" value
 * @method GrupoHigiene        setHigienes() Sets the current record's "Higienes" collection
 * @method GrupoHigiene        setHigiene()  Sets the current record's "Higiene" collections
 * @property Doctrine_Collection $Higiene
 * 
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method Doctrine_Collection getHigienes() Returns the current record's "Higienes" collection
 * @method Doctrine_Collection getHigiene()  Returns the current record's "Higiene" collection
 * @method GrupoHigiene        setNombre()   Sets the current record's "nombre" value
 * @method GrupoHigiene        setHigienes() Sets the current record's "Higienes" collection
 * @method GrupoHigiene        setHigiene()  Sets the current record's "Higiene" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupoHigiene extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo_higiene');
        $this->hasColumn('nombre', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Higiene as Higienes', array(
             'local' => 'id',
             'foreign' => 'forma_cosmetica_id'));

        $this->hasMany('Higiene', array(
             'local' => 'id',
             'foreign' => 'grupo_higiene_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}