<?php

/**
 * BaseRepresentanteLegal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $persona_id
 * @property Persona $Persona
 * @property Empresa $Empresa
 * 
 * @method integer            getPersonaId()  Returns the current record's "persona_id" value
 * @method Persona            getPersona()    Returns the current record's "Persona" value
 * @method Empresa            getEmpresa()    Returns the current record's "Empresa" value
 * @method RepresentanteLegal setPersonaId()  Sets the current record's "persona_id" value
 * @method RepresentanteLegal setPersona()    Sets the current record's "Persona" value
 * @method RepresentanteLegal setEmpresa()    Sets the current record's "Empresa" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRepresentanteLegal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('representante_legal');
        $this->hasColumn('persona_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'persona_id',
             'foreign' => 'id'));

        $this->hasOne('Empresa', array(
             'local' => 'id',
             'foreign' => 'representante_legal_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}