<?php

/**
 * BaseCosmetico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $producto_id
 * @property integer $forma_cosmetica_id
 * @property integer $grupo_cosmetico_id
 * @property integer $marca_id
 * @property integer $pais_id
 * @property string $codigo_nso
 * @property string $vigencia_nso
 * @property string $expediente
 * @property Producto $Producto
 * @property FormaCosmetica $FormaCosmetica
 * @property Doctrine_Collection $GrupoCosmetico
 * @property Marca $Marca
 * @property Pais $Pais
 * 
 * @method integer             getProductoId()         Returns the current record's "producto_id" value
 * @method integer             getFormaCosmeticaId()   Returns the current record's "forma_cosmetica_id" value
 * @method integer             getGrupoCosmeticoId()   Returns the current record's "grupo_cosmetico_id" value
 * @method integer             getMarcaId()            Returns the current record's "marca_id" value
 * @method integer             getPaisId()             Returns the current record's "pais_id" value
 * @method string              getCodigoNso()          Returns the current record's "codigo_nso" value
 * @method string              getVigenciaNso()        Returns the current record's "vigencia_nso" value
 * @method string              getExpediente()         Returns the current record's "expediente" value
 * @method Producto            getProducto()           Returns the current record's "Producto" value
 * @method FormaCosmetica      getFormaCosmetica()     Returns the current record's "FormaCosmetica" value
 * @method Doctrine_Collection getGrupoCosmetico()     Returns the current record's "GrupoCosmetico" collection
 * @method Marca               getMarca()              Returns the current record's "Marca" value
 * @method Pais                getPais()               Returns the current record's "Pais" value
 * @method Cosmetico           setProductoId()         Sets the current record's "producto_id" value
 * @method Cosmetico           setFormaCosmeticaId()   Sets the current record's "forma_cosmetica_id" value
 * @method Cosmetico           setGrupoCosmeticoId()   Sets the current record's "grupo_cosmetico_id" value
 * @method Cosmetico           setMarcaId()            Sets the current record's "marca_id" value
 * @method Cosmetico           setPaisId()             Sets the current record's "pais_id" value
 * @method Cosmetico           setCodigoNso()          Sets the current record's "codigo_nso" value
 * @method Cosmetico           setVigenciaNso()        Sets the current record's "vigencia_nso" value
 * @method Cosmetico           setExpediente()         Sets the current record's "expediente" value
 * @method Cosmetico           setProducto()           Sets the current record's "Producto" value
 * @method Cosmetico           setFormaCosmetica()     Sets the current record's "FormaCosmetica" value
 * @method Cosmetico           setGrupoCosmetico()     Sets the current record's "GrupoCosmetico" collection
 * @method Cosmetico           setMarca()              Sets the current record's "Marca" value
 * @method Cosmetico           setPais()               Sets the current record's "Pais" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCosmetico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cosmetico');
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('forma_cosmetica_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('grupo_cosmetico_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('marca_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pais_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('codigo_nso', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('vigencia_nso', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('expediente', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasOne('FormaCosmetica', array(
             'local' => 'forma_cosmetica_id',
             'foreign' => 'id'));

        $this->hasMany('GrupoCosmetico', array(
             'local' => 'grupo_cosmetico_id',
             'foreign' => 'id'));

        $this->hasOne('Marca', array(
             'local' => 'grupo_cosmetico_id',
             'foreign' => 'id'));

        $this->hasOne('Pais', array(
             'local' => 'pais_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}