<?php

/**
 * BasePais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $bandera
 * @property LaboratorioFabricante $LaboratorioFabricante
 * @property Doctrine_Collection $Ciudades
 * @property Cosmetico $Cosmetico
 * @property Doctrine_Collection $Formularios706
 * @property Doctrine_Collection $Higiene
 * @property Doctrine_Collection $Formulario11
 * 
 * @method string                getNombre()                Returns the current record's "nombre" value
 * @method string                getBandera()               Returns the current record's "bandera" value
 * @method LaboratorioFabricante getLaboratorioFabricante() Returns the current record's "LaboratorioFabricante" value
 * @method Doctrine_Collection   getCiudades()              Returns the current record's "Ciudades" collection
 * @method Cosmetico             getCosmetico()             Returns the current record's "Cosmetico" value
 * @method Doctrine_Collection   getFormularios706()        Returns the current record's "Formularios706" collection
 * @method Doctrine_Collection   getHigiene()               Returns the current record's "Higiene" collection
 * @method Doctrine_Collection   getFormulario11()          Returns the current record's "Formulario11" collection
 * @method Pais                  setNombre()                Sets the current record's "nombre" value
 * @method Pais                  setBandera()               Sets the current record's "bandera" value
 * @method Pais                  setLaboratorioFabricante() Sets the current record's "LaboratorioFabricante" value
 * @method Pais                  setCiudades()              Sets the current record's "Ciudades" collection
 * @method Pais                  setCosmetico()             Sets the current record's "Cosmetico" value
 * @method Pais                  setFormularios706()        Sets the current record's "Formularios706" collection
 * @method Pais                  setHigiene()               Sets the current record's "Higiene" collection
 * @method Pais                  setFormulario11()          Sets the current record's "Formulario11" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pais');
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('bandera', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LaboratorioFabricante', array(
             'local' => 'id',
             'foreign' => 'pais_id'));

        $this->hasMany('Ciudad as Ciudades', array(
             'local' => 'id',
             'foreign' => 'pais_id'));

        $this->hasOne('Cosmetico', array(
             'local' => 'id',
             'foreign' => 'pais_id'));

        $this->hasMany('Formulario706 as Formularios706', array(
             'local' => 'id',
             'foreign' => 'rescom_ciudad_id'));

        $this->hasMany('Higiene', array(
             'local' => 'id',
             'foreign' => 'pais_id'));

        $this->hasMany('Formulario11', array(
             'local' => 'id',
             'foreign' => 'pais_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}