<?php

/**
 * BaseAval
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo
 * @property string $nombre_generico
 * @property string $forma_farmaceutica
 * @property string $concentracion
 * @property string $via_administracion
 * @property string $accion_terapeutica
 * @property string $dosis
 * @property string $indicaciones
 * @property string $contraindicaciones
 * @property string $precauciones
 * @property string $efectos_secundarios
 * @property string $acta_comunicacion
 * @property string $observaciones
 * @property string $comision
 * @property string $calificacion
 * @property Doctrine_Collection $Formulario7
 * @property Doctrine_Collection $TipoCalificacion
 * 
 * @method string              getCodigo()              Returns the current record's "codigo" value
 * @method string              getNombreGenerico()      Returns the current record's "nombre_generico" value
 * @method string              getFormaFarmaceutica()   Returns the current record's "forma_farmaceutica" value
 * @method string              getConcentracion()       Returns the current record's "concentracion" value
 * @method string              getViaAdministracion()   Returns the current record's "via_administracion" value
 * @method string              getAccionTerapeutica()   Returns the current record's "accion_terapeutica" value
 * @method string              getDosis()               Returns the current record's "dosis" value
 * @method string              getIndicaciones()        Returns the current record's "indicaciones" value
 * @method string              getContraindicaciones()  Returns the current record's "contraindicaciones" value
 * @method string              getPrecauciones()        Returns the current record's "precauciones" value
 * @method string              getEfectosSecundarios()  Returns the current record's "efectos_secundarios" value
 * @method string              getActaComunicacion()    Returns the current record's "acta_comunicacion" value
 * @method string              getObservaciones()       Returns the current record's "observaciones" value
 * @method string              getComision()            Returns the current record's "comision" value
 * @method string              getCalificacion()        Returns the current record's "calificacion" value
 * @method Doctrine_Collection getFormulario7()         Returns the current record's "Formulario7" collection
 * @method Doctrine_Collection getTipoCalificacion()    Returns the current record's "TipoCalificacion" collection
 * @method Aval                setCodigo()              Sets the current record's "codigo" value
 * @method Aval                setNombreGenerico()      Sets the current record's "nombre_generico" value
 * @method Aval                setFormaFarmaceutica()   Sets the current record's "forma_farmaceutica" value
 * @method Aval                setConcentracion()       Sets the current record's "concentracion" value
 * @method Aval                setViaAdministracion()   Sets the current record's "via_administracion" value
 * @method Aval                setAccionTerapeutica()   Sets the current record's "accion_terapeutica" value
 * @method Aval                setDosis()               Sets the current record's "dosis" value
 * @method Aval                setIndicaciones()        Sets the current record's "indicaciones" value
 * @method Aval                setContraindicaciones()  Sets the current record's "contraindicaciones" value
 * @method Aval                setPrecauciones()        Sets the current record's "precauciones" value
 * @method Aval                setEfectosSecundarios()  Sets the current record's "efectos_secundarios" value
 * @method Aval                setActaComunicacion()    Sets the current record's "acta_comunicacion" value
 * @method Aval                setObservaciones()       Sets the current record's "observaciones" value
 * @method Aval                setComision()            Sets the current record's "comision" value
 * @method Aval                setCalificacion()        Sets the current record's "calificacion" value
 * @method Aval                setFormulario7()         Sets the current record's "Formulario7" collection
 * @method Aval                setTipoCalificacion()    Sets the current record's "TipoCalificacion" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAval extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aval');
        $this->hasColumn('codigo', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('nombre_generico', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('forma_farmaceutica', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('concentracion', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('via_administracion', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('accion_terapeutica', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('dosis', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('indicaciones', 'string', 5000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5000,
             ));
        $this->hasColumn('contraindicaciones', 'string', 5000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5000,
             ));
        $this->hasColumn('precauciones', 'string', 5000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5000,
             ));
        $this->hasColumn('efectos_secundarios', 'string', 5000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5000,
             ));
        $this->hasColumn('acta_comunicacion', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('observaciones', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('comision', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('calificacion', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Formulario7', array(
             'local' => 'id',
             'foreign' => 'aval_id'));

        $this->hasMany('TipoCalificacion', array(
             'local' => 'tipo_calificacion_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}