<?php

/**
 * BaseHigiene
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $producto_id
 * @property string $grupo_higiene
 * @property integer $marca_id
 * @property integer $pais_id
 * @property boolean $phd
 * @property boolean $pahp
 * @property string $variedad
 * @property string $codigo_nso
 * @property string $vigencia_nso
 * @property string $expediente
 * @property Producto $Producto
 * @property Marca $Marca
 * @property Pais $Pais
 * 
 * @method integer  getProductoId()    Returns the current record's "producto_id" value
 * @method string   getGrupoHigiene()  Returns the current record's "grupo_higiene" value
 * @method integer  getMarcaId()       Returns the current record's "marca_id" value
 * @method integer  getPaisId()        Returns the current record's "pais_id" value
 * @method boolean  getPhd()           Returns the current record's "phd" value
 * @method boolean  getPahp()          Returns the current record's "pahp" value
 * @method string   getVariedad()      Returns the current record's "variedad" value
 * @method string   getCodigoNso()     Returns the current record's "codigo_nso" value
 * @method string   getVigenciaNso()   Returns the current record's "vigencia_nso" value
 * @method string   getExpediente()    Returns the current record's "expediente" value
 * @method Producto getProducto()      Returns the current record's "Producto" value
 * @method Marca    getMarca()         Returns the current record's "Marca" value
 * @method Pais     getPais()          Returns the current record's "Pais" value
 * @method Higiene  setProductoId()    Sets the current record's "producto_id" value
 * @method Higiene  setGrupoHigiene()  Sets the current record's "grupo_higiene" value
 * @method Higiene  setMarcaId()       Sets the current record's "marca_id" value
 * @method Higiene  setPaisId()        Sets the current record's "pais_id" value
 * @method Higiene  setPhd()           Sets the current record's "phd" value
 * @method Higiene  setPahp()          Sets the current record's "pahp" value
 * @method Higiene  setVariedad()      Sets the current record's "variedad" value
 * @method Higiene  setCodigoNso()     Sets the current record's "codigo_nso" value
 * @method Higiene  setVigenciaNso()   Sets the current record's "vigencia_nso" value
 * @method Higiene  setExpediente()    Sets the current record's "expediente" value
 * @method Higiene  setProducto()      Sets the current record's "Producto" value
 * @method Higiene  setMarca()         Sets the current record's "Marca" value
 * @method Higiene  setPais()          Sets the current record's "Pais" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHigiene extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('higiene');
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('grupo_higiene', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('marca_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pais_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('phd', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('pahp', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('variedad', 'string', 2000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 2000,
             ));
        $this->hasColumn('codigo_nso', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('vigencia_nso', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('expediente', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasOne('Marca', array(
             'local' => 'marca_id',
             'foreign' => 'id'));

        $this->hasOne('Pais', array(
             'local' => 'pais_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}