<?php

/**
 * BaseProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_producto_id
 * @property varchar $observacion
 * @property CodigoProducto $CodigoProducto
 * @property Medicamento $Medicamento
 * @property DispositivoMedico $DispositivoMedico
 * @property Cosmetico $Cosmetico
 * @property Higiene $Higiene
 * @property Reactivo $Reactivo
 * @property Item $Item
 * @property Doctrine_Collection $Formulario7
 * 
 * @method integer             getCodigoProductoId()   Returns the current record's "codigo_producto_id" value
 * @method varchar             getObservacion()        Returns the current record's "observacion" value
 * @method CodigoProducto      getCodigoProducto()     Returns the current record's "CodigoProducto" value
 * @method Medicamento         getMedicamento()        Returns the current record's "Medicamento" value
 * @method DispositivoMedico   getDispositivoMedico()  Returns the current record's "DispositivoMedico" value
 * @method Cosmetico           getCosmetico()          Returns the current record's "Cosmetico" value
 * @method Higiene             getHigiene()            Returns the current record's "Higiene" value
 * @method Reactivo            getReactivo()           Returns the current record's "Reactivo" value
 * @method Item                getItem()               Returns the current record's "Item" value
 * @method Doctrine_Collection getFormulario7()        Returns the current record's "Formulario7" collection
 * @method Producto            setCodigoProductoId()   Sets the current record's "codigo_producto_id" value
 * @method Producto            setObservacion()        Sets the current record's "observacion" value
 * @method Producto            setCodigoProducto()     Sets the current record's "CodigoProducto" value
 * @method Producto            setMedicamento()        Sets the current record's "Medicamento" value
 * @method Producto            setDispositivoMedico()  Sets the current record's "DispositivoMedico" value
 * @method Producto            setCosmetico()          Sets the current record's "Cosmetico" value
 * @method Producto            setHigiene()            Sets the current record's "Higiene" value
 * @method Producto            setReactivo()           Sets the current record's "Reactivo" value
 * @method Producto            setItem()               Sets the current record's "Item" value
 * @method Producto            setFormulario7()        Sets the current record's "Formulario7" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProducto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto');
        $this->hasColumn('codigo_producto_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('observacion', 'varchar', 2000, array(
             'type' => 'varchar',
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CodigoProducto', array(
             'local' => 'codigo_producto_id',
             'foreign' => 'id'));

        $this->hasOne('Medicamento', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasOne('DispositivoMedico', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasOne('Cosmetico', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasOne('Higiene', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasOne('Reactivo', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasOne('Item', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $this->hasMany('Formulario7', array(
             'local' => 'id',
             'foreign' => 'producto_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}