<?php

/**
 * BaseComentarioTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $tarea_id
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Tarea
 * @property Doctrine_Collection $sfGuardUser
 * 
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getTareaId()     Returns the current record's "tarea_id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTarea()       Returns the current record's "Tarea" collection
 * @method Doctrine_Collection getSfGuardUser() Returns the current record's "sfGuardUser" collection
 * @method ComentarioTarea     setUserId()      Sets the current record's "user_id" value
 * @method ComentarioTarea     setTareaId()     Sets the current record's "tarea_id" value
 * @method ComentarioTarea     setNombre()      Sets the current record's "nombre" value
 * @method ComentarioTarea     setDescripcion() Sets the current record's "descripcion" value
 * @method ComentarioTarea     setTarea()       Sets the current record's "Tarea" collection
 * @method ComentarioTarea     setSfGuardUser() Sets the current record's "sfGuardUser" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentarioTarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario_tarea');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tarea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('descripcion', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tarea', array(
             'local' => 'tare_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}