<?php

/**
 * BaseComentarioTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tarea_id
 * @property string $comentario
 * @property boolean $leido
 * @property Doctrine_Collection $Tarea
 * @property Doctrine_Collection $sfGuardUser
 * 
 * @method integer             getTareaId()     Returns the current record's "tarea_id" value
 * @method string              getComentario()  Returns the current record's "comentario" value
 * @method boolean             getLeido()       Returns the current record's "leido" value
 * @method Doctrine_Collection getTarea()       Returns the current record's "Tarea" collection
 * @method Doctrine_Collection getSfGuardUser() Returns the current record's "sfGuardUser" collection
 * @method ComentarioTarea     setTareaId()     Sets the current record's "tarea_id" value
 * @method ComentarioTarea     setComentario()  Sets the current record's "comentario" value
 * @method ComentarioTarea     setLeido()       Sets the current record's "leido" value
 * @method ComentarioTarea     setTarea()       Sets the current record's "Tarea" collection
 * @method ComentarioTarea     setSfGuardUser() Sets the current record's "sfGuardUser" collection
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentarioTarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario_tarea');
        $this->hasColumn('tarea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('comentario', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('leido', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tarea', array(
             'local' => 'tare_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}