<?php

/**
 * BaseIngrediente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property DetalleFormulaCc $DetalleFormulaCc
 * 
 * @method string           getNombre()           Returns the current record's "nombre" value
 * @method DetalleFormulaCc getDetalleFormulaCc() Returns the current record's "DetalleFormulaCc" value
 * @method Ingrediente      setNombre()           Sets the current record's "nombre" value
 * @method Ingrediente      setDetalleFormulaCc() Sets the current record's "DetalleFormulaCc" value
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIngrediente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ingrediente');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DetalleFormulaCc', array(
             'local' => 'id',
             'foreign' => 'ingrediente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}