producto_prodmed:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto
    module:               prodmed
    prefix_path:          /prodmed
    column:               id
    with_wildcard_routes: true

ingrediente:
  class: sfDoctrineRouteCollection
  options:
    model:                Ingrediente
    module:               ingredientes
    prefix_path:          /ingredientes
    column:               id
    with_wildcard_routes: true

detalle_formula_cc:
  class: sfDoctrineRouteCollection
  options:
    model:                DetalleFormulaCc
    module:               detallescc
    prefix_path:          /detallescc
    column:               id
    with_wildcard_routes: true

formula_cc:
  class: sfDoctrineRouteCollection
  options:
    model:                FormulaCc
    module:               formulas
    prefix_path:          /formulas
    column:               id
    with_wildcard_routes: true

tipo_venta:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoVenta
    module:               tventas
    prefix_path:          /tventas
    column:               id
    with_wildcard_routes: true

via_administracion:
  class: sfDoctrineRouteCollection
  options:
    model:                ViaAdministracion
    module:               administraciones
    prefix_path:          /administraciones
    column:               id
    with_wildcard_routes: true

forma_farmaceutica:
  class: sfDoctrineRouteCollection
  options:
    model:                FormaFarmaceutica
    module:               ffarmaceuticas
    prefix_path:          /ffarmaceuticas
    column:               id
    with_wildcard_routes: true

medicamento:
  class: sfDoctrineRouteCollection
  options:
    model:                Medicamento
    module:               medicamentos
    prefix_path:          /medicamentos
    column:               id
    with_wildcard_routes: true

producto:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto
    module:               productos
    prefix_path:          /productos
    column:               id
    with_wildcard_routes: true

buscar_ingrediente:
    url:   /ingredientes/buscar
    param: { module: ingredientes, action: buscar }
buscar_labs:
    url:   /laboratorios/buscar
    param: { module: laboratorios, action: buscar }
buscar_representantes:
    url:   /personalegal/buscar
    param: { module: personalegal, action: buscar }
buscar_regentes:
    url:   /personaregente/buscar
    param: { module: personaregente, action: buscar }
persona_personalegal:
  class: sfDoctrineRouteCollection
  options:
    model:                Persona
    module:               personalegal
    prefix_path:          /personalegal
    column:               id
    with_wildcard_routes: true

persona_personaregente:
  class: sfDoctrineRouteCollection
  options:
    model:                Persona
    module:               personaregente
    prefix_path:          /personaregente
    column:               id
    with_wildcard_routes: true

persona:
  class: sfDoctrineRouteCollection
  options:
    model:                Persona
    module:               personafarm
    prefix_path:          /personafarm
    column:               id
    with_wildcard_routes: true

pais:
  class: sfDoctrineRouteCollection
  options:
    model:                Pais
    module:               paises
    prefix_path:          /paises
    column:               id
    with_wildcard_routes: true

representante_legal:
  class: sfDoctrineRouteCollection
  options:
    model:                RepresentanteLegal
    module:               representantes
    prefix_path:          /representantes
    column:               id
    with_wildcard_routes: true

regente_farmaceutico:
  class: sfDoctrineRouteCollection
  options:
    model:                RegenteFarmaceutico
    module:               regentes
    prefix_path:          /regentes
    column:               id
    with_wildcard_routes: true

laboratorio_fabricante:
  class: sfDoctrineRouteCollection
  options:
    model:                LaboratorioFabricante
    module:               laboratorios
    prefix_path:          /laboratorios
    column:               id
    with_wildcard_routes: true

empresa:
  class: sfDoctrineRouteCollection
  options:
    model:                Empresa
    module:               empresas
    prefix_path:          /empresas
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
