generator:
  class: sfDoctrineGenerator
  param:
    model_class:           formulario27
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario27
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha:                     {label: 'Fecha', date_format: dd/MM/yyyy}
        tipo_tramite_formulario27: {label: 'Tipo de Trámite'}
        empresa:                   {label: 'Empresa'}
        laboratorio_fabricante:    {label: 'Laboratorio fabricante'}
        
      list:
        title: Listado de formularios 027
        table_method: selectForms27DeEmpresa
        display: [dispositivo_medico, tipo_tramite_formulario27, laboratorio_fabricante, fecha, etapa]
        batch_actions:  {}
        actions:
          ir_portal:    {label: Volver al portal}
        object_actions:
          etapa: {label: Seguimiento, action: etapa}
          show:  {label: Información, action: show}
      filter:  
        display: [datos_formulario27_id, tipo_tramite_formulario27_id, origen_formulario_id]
      
      form:    ~
      edit:    ~
      new:     ~
