generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Etapa
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          etapa
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de etapas de formularios
        table_method: selectEtapasDeEmpresa
        display: [formulario, tipo_etapa, observacion]
        actions:
          adm_empresa: {label: Volver a Empresa}
          _new: ~ 
      filter:
        display: [formulario_id, tipo_etapa_id, fecha]
      form:    ~
      edit:
        title: Editar etapa de producto
        display: [descripcion, observacion, fecha]
      new:
        title: Nueva etapa de producto
        display: [tipo_etapa_id, descripcion, observacion, fecha]
