generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Formulario27
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario27
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha:                         {label: 'Fecha de Registro'}
        datos_formulario27_id:         {label: 'Datos'}
        tipo_tramite_formulario27_id:  {label: 'Tipo de Trámite'}
        origen_formulario_id:          {label: 'Origen'}
        empresa:                      {label: 'Empresa'}
        laboratorio_fabricante:       {label: 'Laboratorio Fabricante'}
        tipo_tramite_formulario27:     {label: 'Tipo de Trámite'}
      
      list:    
        title: Listado de Solicitudes para Registro y Control de Calidad de Dispositivos Medicos
        display: [fecha, tipo_tramite_formulario27, empresa, laboratorio_fabricante, dispositivo_medico]
        table_method: selectForms27DeDispositivo
        object_actions:
          imprimir: {label: Imprimir, action: print}
          etapa:    {label: Etapa}
          _edit: ~
          _delete: ~
        actions:
          ir_productos: {label: Regresar a Dispositivos}
          ir_empresa:   {label: Volver a Empresa}
          _new: ~      
      filter:  
        display: [datos_formulario27_id, tipo_tramite_formulario27_id, origen_formulario_id]
      
      form:    
        display: 
          Datos Formulario:                 [fecha, datos_formulario27_id, tipo_tramite_formulario27_id, origen_formulario_id]
          DATOS ADICIONALES DEL FORMULARIO: [registro_sanitario, vigencia, fecha_inicio_vigencia, numero_ruta]
      edit:    
        title: Editar Listado de Solicitudes para Registro y Control de Calidad de Dispositivos Medicos
        actions:
          _list: ~  
          _save: ~  
      new:     
        title: Solicitud para Registro y Control de Calidad de Dispositivos Medicos
        actions:
          _list: ~  
          _save: ~