generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user_usuarios
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: 
        username:       {label: Usuario}
        algorithm:      {label: Algoritmo}
        password:       {label: Contraseña}
        is_active:      {label: 'Esta activo?'}
        is_super_admin: {label: 'Es super-usuario?'}
      list:    
        title: Listado de Usuarios Registrados
        max_per_page: 15
        display: [username]
        actions:
          ir_portal: {label: Ir a Portal}
          _new: ~
      filter:  
        display: [username]
      form:
        display: [username, is_active, is_super_admin]
      edit: 
        title: Editar Usuario %%username%%
      new:
        title: Registro de Usuario
