generator:
  class: sfDoctrineGenerator
  param:
    model_class:           formulario12
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario12
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha:                     {label: 'Fecha', date_format: dd/MM/yyyy}
        tipo_tramite_formulario12: {label: 'Tipo de Trámite'}
        origen_formulario_id:      {label: 'Origen'}
        empresa:                   {label: 'Empresa'}
        laboratorio_fabricante:    {label: 'Laboratorio fabricante'}
      list:
        title: Listado de formulario 012
        table_method: selectForms12DeEmpresa
        display: [reactivo, tipo_tramite_formulario12, laboratorio_fabricante, fecha, etapa]
        batch_actions:  {}
        actions:
          ir_portal:    {label: Volver al portal}
        object_actions:
          etapa: {label: Seguimiento, action: etapa}
          show:  {label: Información, action: show}
      filter:
        display: [numero_ruta, tipo_tramite_formulario12_id, origen_formulario_id]
      form:    ~
      edit:    ~
      new:     ~
