<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/11 13:52:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=anbeed',
  'username' => 'mario',
  'password' => 'admin',
  'name' => 'doctrine',
)),);
