<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/11 13:52:13
sfConfig::add(array(
  'mod_personaregente_enabled' => true,
  'mod_personaregente_view_class' => 'sfPHP',
));
