generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Empresa
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          empresa
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        regente_farmaceutico_id:  {label: 'Regente Farmacéutico'}
        representante_legal_id:   {label: 'Representante Legal'}
        razon_social:             {label: 'Razón Social'}
        fecha_registro:           {label: 'Fecha de Registro'}
        num_resolucion:           {label: 'Número de Resolución Ministerial'}
        fecha_resolucion:         {label: 'Fecha de Resolución Ministerial', date_format: 'dd/MM/yyyy'}
        direccion:                {label: 'Dirección'}
        telefono1:                {label: 'Teléfono 1'}
        telefono2:                {label: 'Teléfono 2'}
        registro_camara:          {label: 'Registro en la Cámara Nacional de Industria y/o Comercio'}
        fundempresa:              {label: 'Fundaempresa'}
        nit:                      {label: 'NIT'}
        
      list:
        title: Listado de Empresas Registradas
        display: [razon_social, nit]
        object_actions:
          adm_empresa: {label: Administrar Empresa, action: administrarEmpresa}
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter:
        display: [razon_social, nit]
      form:
        display:
          Datos: [razon_social, fecha_registro, fecha_resolucion, num_resolucion, fax, direccion, casilla, telefono1, telefono1, telefono2, email, actividad, registro_camara, fundempresa, nit, licencia_funcionamiento]
        actions:
          ir_empresa: {label: Volver a Empresa}
          _save: ~
      edit:
        title: Editar Empresa %%razon_social%%
      new:
        title: Registro de Empresas
        actions:
          _list: ~
          _save: ~
