generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TipoTramiteFormulario5
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tipo_tramite_formulario5
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Tipos de Tramite Registrados
        display: [nombre]
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter:  
        display: [nombre]
      form:    
        display: [nombre]
      edit:    
        title: Editar Tipo de Tramite %%nombre%%
      new: 
        title: Registro de Tipos de Tramite
