generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TipoVenta
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tipo_venta
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        actions:
          _save: ~
          cerrar:
      edit:    ~
      new:     
        title: Registro Tipo de Venta
