generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Formulario5
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario5
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        fecha:                        {label: 'Fecha de Registro'}
        tipo_tramite_formulario5_id:  {label: 'Tipo de Trámite'}
        tipo_producto_formulario5_id: {label: 'Tipo de Producto'}
        origen_formulario5_id:        {label: 'Origen'}
      
      list:    
        title: Listado de Solicitudes para Registro y Control de Calidad de Medicamentos
        display: [fecha, tipo_tramite_formulario5, tipo_producto_formulario5, origen_formulario5, producto]
        
      filter:  ~
      
      form:    
      
      edit:    
        title: Editar Listado de Solicitudes para Registro y Control de Calidad de Medicamentos
        display: [fecha, tipo_tramite_formulario5_id, tipo_producto_formulario5_id, origen_formulario5_id, producto_id]
     
      new:     
        title: Solicitud para Registro y Control de Calidad de Medicamentos
        display: [fecha, tipo_tramite_formulario5_id, tipo_producto_formulario5_id, origen_formulario5_id, producto_id]
