generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Persona
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          persona
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        ap_paterno:       {label: 'Apellido Paterno'}
        ap_materno:       {label: 'Apellido Materno'}
        ap_casada:        {label: 'Apellido Casada'}
        cedula_expedido:  {label: 'Cédula de identidad'}
        ci:               {label: 'Cédula de Identidad'}
        expedido:         {label: 'Expedido'}
        direccion:        {label: 'Dirección'}
        telefono:         {label: 'Teléfono'}
        celular:          {label: 'Celular'}
        fax:              {label: 'Fax'}
        casilla:          {label: 'Casilla'}
        email:            {label: 'Email'}
        nombre_ordenado:  {label: 'Persona'}
        username:         {label: 'Usuario'}
        is_active:        {label: 'Activo?'}
        fecha_nacimiento: {label: 'Fecha de nacimiento'}
        foto:             {label: 'Fotografia del usuario'}  
      list:    ~
      filter:  ~
      form:    
        display:
            Datos Personales:  [_verfoto, foto, nombre, ap_paterno, ap_materno, ap_casada, ci, expedido, direccion, telefono, celular, email, fecha_nacimiento]
      edit:    
        title: Editar Perfil de Usuario
        actions:
            ir_portal: {label: Volver al Portal}
            _save: ~  
      new:     ~
