sf_guard_user_cliente_usuario:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               cliente_usuario
    prefix_path:          /cliente_usuario
    column:               id
    with_wildcard_routes: true

cliente:
  class: sfDoctrineRouteCollection
  options:
    model:                Cliente
    module:               clientes
    prefix_path:          /clientes
    column:               id
    with_wildcard_routes: true

persona_persona_usuario:
  class: sfDoctrineRouteCollection
  options:
    model:                Persona
    module:               persona_usuario
    prefix_path:          /persona_usuario
    column:               id
    with_wildcard_routes: true

producto_caducidad:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto
    module:               caducidad
    prefix_path:          /caducidad
    column:               id
    with_wildcard_routes: true

grupo_higiene:
  class: sfDoctrineRouteCollection
  options:
    model:                GrupoHigiene
    module:               ghigiene
    prefix_path:          /ghigiene
    column:               id
    with_wildcard_routes: true

grupo_cosmetico:
  class: sfDoctrineRouteCollection
  options:
    model:                GrupoCosmetico
    module:               gcosmetico
    prefix_path:          /gcosmetico
    column:               id
    with_wildcard_routes: true

formulario12:
  class: sfDoctrineRouteCollection
  options:
    model:                Formulario12
    module:               formulario12
    prefix_path:          /formulario12
    column:               id
    with_wildcard_routes: true

producto:
  class: sfDoctrineRouteCollection
  options:
    model:                Producto
    module:               productos
    prefix_path:          /productos
    column:               id
    with_wildcard_routes: true

listar_productos:
    url:   /productos/buscar
    param: { module: productos, action: buscar }

codigo_producto:
  class: sfDoctrineRouteCollection
  options:
    model:                CodigoProducto
    module:               codprod
    prefix_path:          /codprod
    column:               id
    with_wildcard_routes: true

emisor:
  class: sfDoctrineRouteCollection
  options:
    model:                Emisor
    module:               emisor
    prefix_path:          /emisor
    column:               id
    with_wildcard_routes: true

tipo_documento:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoDocumento
    module:               tipodoc
    prefix_path:          /tipodoc
    column:               id
    with_wildcard_routes: true

emision_correspondencia:
  class: sfDoctrineRouteCollection
  options:
    model:                EmisionCorrespondencia
    module:               emisionc
    prefix_path:          /emisionc
    column:               id
    with_wildcard_routes: true

formulario706:
  class: sfDoctrineRouteCollection
  options:
    model:                Formulario706
    module:               formulario706
    prefix_path:          /formulario706
    column:               id
    with_wildcard_routes: true

formulario516:
  class: sfDoctrineRouteCollection
  options:
    model:                Formulario516
    module:               formulario516
    prefix_path:          /formulario516
    column:               id
    with_wildcard_routes: true

ciudad:
  class: sfDoctrineRouteCollection
  options:
    model:                Ciudad
    module:               ciudades
    prefix_path:          /ciudades
    column:               id
    with_wildcard_routes: true
    
formulario27:
  class: sfDoctrineRouteCollection
  options:
    model:                Formulario27
    module:               formulario27
    prefix_path:          /formulario27
    column:               id
    with_wildcard_routes: true

formulario5:
  class: sfDoctrineRouteCollection
  options:
    model:                Formulario5
    module:               formulario5
    prefix_path:          /formulario5
    column:               id
    with_wildcard_routes: true

via_administracion:
  class: sfDoctrineRouteCollection
  options:
    model:                ViaAdministracion
    module:               administraciones
    prefix_path:          /administraciones
    column:               id
    with_wildcard_routes: true

tipo_venta:
  class: sfDoctrineRouteCollection
  options:
    model:                TipoVenta
    module:               tventas
    prefix_path:          /tventas
    column:               id
    with_wildcard_routes: true

pais:
  class: sfDoctrineRouteCollection
  options:
    model:                Pais
    module:               paises
    prefix_path:          /paises
    column:               id
    with_wildcard_routes: true

laboratorio_fabricante:
  class: sfDoctrineRouteCollection
  options:
    model:                LaboratorioFabricante
    module:               laboratorios
    prefix_path:          /laboratorios
    column:               id
    with_wildcard_routes: true

ingrediente:
  class: sfDoctrineRouteCollection
  options:
    model:                Ingrediente
    module:               ingredientes
    prefix_path:          /ingredientes
    column:               id
    with_wildcard_routes: true

sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               permisos
    prefix_path:          /permisos
    column:               id
    with_wildcard_routes: true

persona:
  class: sfDoctrineRouteCollection
  options:
    model:                Persona
    module:               personas
    prefix_path:          /personas
    column:               id
    with_wildcard_routes: true

sf_guard_user_usuarios:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               usuarios
    prefix_path:          /usuarios
    column:               id
    with_wildcard_routes: true

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               grupos
    prefix_path:          /grupos
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               usuario
    prefix_path:          /usuario
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
