ingrediente:
  class: sfDoctrineRouteCollection
  options:
    model:                Ingrediente
    module:               ingredientes
    prefix_path:          /ingredientes
    column:               id
    with_wildcard_routes: true

sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               permisos
    prefix_path:          /permisos
    column:               id
    with_wildcard_routes: true

persona:
  class: sfDoctrineRouteCollection
  options:
    model:                Persona
    module:               personas
    prefix_path:          /personas
    column:               id
    with_wildcard_routes: true

sf_guard_user_usuarios:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               usuarios
    prefix_path:          /usuarios
    column:               id
    with_wildcard_routes: true

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               grupos
    prefix_path:          /grupos
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               usuario
    prefix_path:          /usuario
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
