generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EmisionCorrespondencia
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          emision_correspondencia
    with_doctrine_route:   true 
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: 
        tipo_documento_id:      {label: 'tipo de documento' }
        tipo_documento:         {label: 'Tipo de Documento' }
        factura:                {label: 'Nº factura' }
        factura_fecha:          {label: 'fecha de factura' }
        monto_item:             {label: 'monto Bs. y item' }
        nombre:                 {label: 'Detalle o Nombre' }
        numero:                 {label: 'Nº Reg. San. o despacho' }
        codigo_producto_id:     {label: 'código de producto' }
        fecha_inicio_vigencia:  {label: 'Fecha de reg. san. o despacho' }
        vigencia:               {label: 'plazo de vencimiento' }
        fecha_envio:            {label: 'Fecha de Envío' }
        numero_guia:            {label: 'Número de Guía' }
      list:
        title:   Listado Emisión de Correspondencia
        sort:    [id, desc]
        display: [tipo_documento, emisor, nombre, fecha_envio, numero_guia]
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter:  
        display: [tipo_documento_id, empresa_id, emisor_id, nombre, fecha_envio, numero_guia]
      form:    
        display:
          Datos del Envío:                  [fecha_envio, numero_guia, tipo_documento_id, empresa_id, emisor_id, nombre]
          En caso de Factura:               [factura, factura_fecha, monto_item]
          En caso de Productos o Despachos: [numero, codigo_producto_id, fecha_inicio_vigencia, vigencia]
      edit:    
        title:   Editar Emisión de Correspondencia
      new:     
        title:   Registrar Emisión de Correspondencia
