<?php

/**
 * CodigoProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodigoProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodigoProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CodigoProducto');
    }
}