<?php

/**
 * CosmeticoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CosmeticoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CosmeticoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cosmetico');
    }
}