<?php

/**
 * DatosFormulario27Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatosFormulario27Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatosFormulario27Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DatosFormulario27');
    }
}