<?php

/**
 * DispositivoMedicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DispositivoMedicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DispositivoMedicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DispositivoMedico');
    }
    
    public function selectDispositivosDeEmpresa()
    {
        $user = sfContext::getInstance()->getUser();
        $empresa = $user->getAttribute('empresa');
        $q = Doctrine_Query::create()
                    ->from('DispositivoMedico d')
                    ->where('d.empresa_id = ?', $empresa->getId())
                    ->orderBy('d.id ASC');
            
        return $q;
    }
}