<?php

/**
 * DispositivoMedicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DispositivoMedicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DispositivoMedicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DispositivoMedico');
    }
}