<?php

/**
 * EmisionCorrespondenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmisionCorrespondenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmisionCorrespondenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmisionCorrespondencia');
    }
    
}