<?php

/**
 * FormularioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormularioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormularioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formulario');
    }
}