<?php

/**
 * FormaFarmaceuticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormaFarmaceuticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormaFarmaceuticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormaFarmaceutica');
    }
}