<?php

/**
 * Formulario11
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Formulario11 extends BaseFormulario11
{
    public function getTipo()
    {
        $otro = "";
        if($this->getTipoDespachoId() == 5)
            $otro = " - ".$this->getOtro();
        return $this->TipoDespacho."".$otro ;
    }
    
    public function getEtapa()
    {
        return $this->Formulario->Etapa[0]->TipoEtapa->getNombre();
    }
}
