<?php

/**
 * Formulario516
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Formulario516 extends BaseFormulario516
{
    public function getLaboratorio() 
    {
        return $this->Cosmetico->LaboratorioFabricante;
    }
    public function getEmpresa()
    {
        return $this-> Cosmetico -> Empresa;
    }
}
