<?php

/**
 * Formulario5Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Formulario5Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Formulario5Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formulario5');
    }
    public function selectForms5DeMedicamento()
    {
        $user = sfContext::getInstance()->getUser();
        $medicamento = $user->getAttribute('medicamento');
        $q = Doctrine_Query::create()
            ->from('Formulario5 f')
            ->leftJoin('f.TipoTramiteFormulario5 tf')
            ->leftJoin('f.TipoProductoFormulario5 tp')
            ->leftJoin('f.OrigenFormulario of')
            ->leftJoin('f.Formulario u')
            ->leftJoin('u.Etapa e')
            ->where('f.medicamento_id = ?', $medicamento->getId())
            ->orderBy('f.created_at DESC')
            ->addOrderBy('e.created_at DESC');
            
        return $q;
    }
    
    public function selectForms5DeEmpresa()
    {
        $user = sfContext::getInstance()->getUser();
        $empresa = $user->getAttribute('empresa');
        $q = Doctrine_Query::create()
            ->from('Formulario5 f')
            ->leftJoin('f.Medicamento p')
            ->leftJoin('p.Empresa e') 
            ->where('p.empresa_id = ?', $empresa->getId())
            ->orderBy('f.id ASC');
        return $q;
    }
}