<?php

/**
 * Formulario706
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Formulario706 extends BaseFormulario706
{
    public function getEmpresa()
    {
        return $this-> Higiene -> Empresa;
    }
    
    public function getLaboratorioFabricante()
    {
        return $this-> Higiene -> LaboratorioFabricante;
    }
}
