<?php

/**
 * Formulario11Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Formulario11Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Formulario11Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formulario11');
    }
}