<?php

/**
 * Formulario11Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Formulario11Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Formulario11Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formulario11');
    }
    
    public function selectForm11DeEmpresa()
    {
        $user = sfContext::getInstance()->getUser();
        $empresa = $user->getAttribute('empresa');
        $q = Doctrine_Query::create()
            ->from('Formulario11 f')
            ->leftJoin('f.Formulario u')
            ->leftJoin('u.Etapa e')
            ->where('f.empresa_id = ?', $empresa->getId())
            ->orderBy('f.created_at DESC')
            ->addOrderBy('e.created_at DESC');
        return $q;
    }
    
    public function selectFormulario11DeEmpresa($id)
    {
//        $user = sfContext::getInstance()->getUser();
//        $empresa = $user->getAttribute('empresa');
        
        $q = Doctrine_Query::create()
            ->from('Formulario11 f')
            //->leftJoin('f.Reactivo r')
//            ->leftJoin('r.Empresa e')
            //->leftJoin('f.TipoTramiteFormulario12 tf')
            //->leftJoin('f.OrigenFormulario of')
            ->leftJoin('f.Formulario u')
            ->leftJoin('u.Etapa et')
            ->addWhere('f.id = ?', $id)
            ->orderBy('f.created_at DESC')
            ->addOrderBy('et.created_at DESC');
        return $q;
        
    }
    
}