<?php

/**
 * Formulario27Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Formulario27Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Formulario27Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formulario27');
    }
    
    public function selectForms27DeDispositivo()
    {
        $user = sfContext::getInstance()->getUser();
        $dispositivo = $user->getAttribute('dispositivo_medico');
        $q = Doctrine_Query::create()
            ->from('Formulario27 f')
            ->leftJoin('f.TipoTramiteFormulario27 tf')
            ->leftJoin('f.DatosFormulario27 df')
            ->leftJoin('f.OrigenFormulario of')
            ->leftJoin('f.Formulario u')
            ->leftJoin('u.Etapa e')
            ->where('f.dispositivo_medico_id = ?', $dispositivo->getId())
            ->orderBy('f.created_at DESC')
            ->addOrderBy('e.created_at DESC');
            
        return $q;
    }
    
    public function selectForms27DeEmpresa()
    {
        $user = sfContext::getInstance()->getUser();
        $empresa = $user->getAttribute('empresa');
        
        $q = Doctrine_Query::create()
            ->from('Formulario27 f')
            ->leftJoin('f.DispositivoMedico d')
            ->leftJoin('f.Formulario u')
            ->leftJoin('u.Etapa e')
            ->where('d.empresa_id = ?', $empresa->getId())
            ->orderBy('f.id ASC')
            ->addOrderBy('e.created_at DESC');
        
        return $q;
    }
}