<?php

/**
 * Formulario11Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Formulario11Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Formulario11Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formulario11');
    }
    
    public function selectForm11DeEmpresa()
    {
        $user = sfContext::getInstance()->getUser();
        $empresa = $user->getAttribute('empresa');
        $q = Doctrine_Query::create()
                    ->from('Formulario11 f')
//                    ->leftJoin('f.Medicamento p')
//                    ->leftJoin('p.Empresa e') 
                    ->where('f.empresa_id = ?', $empresa->getId())
                    ->orderBy('f.id ASC');
        return $q;
    }
}