<?php

/**
 * Formulario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Formulario extends BaseFormulario
{
    public function __toString()
    {
        if($this->Formulario5->getId())
        {
            return $this->Formulario5->Medicamento->getNombreComercial();
        }
        if($this->Formulario27->getId())
        {
            return $this->Formulario27->DispositivoMedico->getNombreComercial();
        }
        if($this->Formulario516->getId())
        {
            return $this->Formulario516->Cosmetico->getNombre();
        }
        if($this->Formulario706->getId())
        {
            return $this->Formulario706->Higiene->getNombre();
        }
        if($this->Formulario11->getId())
        {
            //return 'asdasd';
            return ''.$this->Formulario11->getNumeroRuta();
        }
        if($this->Formulario12->getId())
        {
            return $this->Formulario12->Reactivo->getNombreComercial();
        }
    }
}
