<?php

/**
 * Formulario706Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Formulario706Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Formulario706Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Formulario706');
    }
}