<?php

/**
 * FormulaCcTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormulaCcTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormulaCcTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormulaCc');
    }
}