<?php

/**
 * HigieneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HigieneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HigieneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Higiene');
    }
}