<?php

/**
 * IngredienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IngredienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IngredienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ingrediente');
    }
}