<?php

/**
 * IniciacionFormularioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IniciacionFormularioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IniciacionFormularioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IniciacionFormulario');
    }
    
    public function selectEtapasDeEmpresa()
    {
        $user = sfContext::getInstance()->getUser();
        $empresa = $user->getAttribute('empresa');
        
        $q = Doctrine_Query::create()
            ->from('IniciacionFormulario i')
            ->where('i.empresa_id = ?', $empresa->getId())
            ->orderBy('i.created_at DESC');
            
        return $q;
    }
}