<?php

/**
 * LaboratorioFabricanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LaboratorioFabricanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LaboratorioFabricanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LaboratorioFabricante');
    }
}