<?php

/**
 * MedicamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medicamento');
    }
    public function selectMedicamentosDeEmpresa()
    {
        $user = sfContext::getInstance()->getUser();
        $empresa = $user->getAttribute('empresa');
        $q = Doctrine_Query::create()
                    ->from('Medicamento m')
                    ->where('m.empresa_id = ?', $empresa->getId())
                    ->orderBy('m.id ASC');
            
        return $q;
    }
}