<?php

/**
 * NotificacionClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificacionClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotificacionClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotificacionCliente');
    }
    
    public function selectNotificacionesOrdenadas()
    {
        $q = Doctrine_Query::create()
                    ->from('NotificacionCliente n')
                    ->orderBy('n.created_at DESC');
            
        return $q;
    }
}