<?php

/**
 * OrigenFormulario5Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrigenFormulario5Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrigenFormulario5Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrigenFormulario5');
    }
}