<?php

/**
 * OrigenFormularioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrigenFormularioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrigenFormularioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrigenFormulario');
    }
}