<?php

/**
 * PersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Persona');
    }
    
    public static function selectPersonasDisponibles()
    {
        //$user = sfContext::getInstance()->getUser();
       
        $q = Doctrine_Query::create()
                ->from('Persona a')
                ->leftJoin('a.sfGuardUser u')
                ->where('a.is_active = ?', true)
                ->addWhere('u.id is NULL')
                ->orderBy('a.ap_paterno');
        
        return $q;
       
    }
    public static function selectUsuariosDisponibles()
    {
        //$user = sfContext::getInstance()->getUser();
       
        $q = Doctrine_Query::create()
                ->from('Persona a')
                ->innerJoin('a.sfGuardUser u')
                ->where('a.is_active = ?', true)
                ->orderBy('a.ap_paterno');
        
        return $q;
       
    }
    
    
}