<?php

/**
 * PrincipioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrincipioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrincipioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Principio');
    }
}