<?php

/**
 * Producto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Producto extends BaseProducto
{
    public function __toString()
    {
       if(isset($this->Medicamento))
       {
           return $this->CodigoProducto->getNombre()." - ".$this->Medicamento->getNombreComercial();
       }
       else if(isset($this->DispositivoMedico))
       {  
           return $this->CodigoProducto->getNombre()." - ".$this->DispositivoMedico->getNombreComercial();
       } 
       else if(isset($this->Cosmetico))
       {  
           return $this->CodigoProducto->getNombre()." - ".$this->Cosmetico->getNombre();
       } 
       else if(isset($this->Higiene))
       {  
           return $this->CodigoProducto->getNombre()." - ".$this->Higiene->getNombre();
       }
       else
           return $this->CodigoProducto->getNombre()." - ".$this->Reactivo->getNombreComercial();
    }
    
    public function getProducto()
    {
       if(isset($this->Medicamento))
       {
           return $this->CodigoProducto->getNombre()." - ".$this->Medicamento->getNombreComercial();
       }
       else if(isset($this->DispositivoMedico))
       {  
           return $this->CodigoProducto->getNombre()." - ".$this->DispositivoMedico->getNombreComercial();
       } 
       else if(isset($this->Cosmetico))
       {  
           return $this->CodigoProducto->getNombre()." - ".$this->Cosmetico->getNombre();
       } 
       else if(isset($this->Higiene))
       {  
           return $this->CodigoProducto->getNombre()." - ".$this->Higiene->getNombre();
       }
       else
           return $this->CodigoProducto->getNombre()." - ".$this->Reactivo->getNombreComercial();
    }
    
    public function getEmpresa()
    {
       if(isset($this->Medicamento))
       {
           $this->Medicamento->Empresa->getRazonSocial();
       }
       else if(isset($this->DispositivoMedico))
       {  
           return $this->DispositivoMedico->Empresa->getRazonSocial();
       } 
       else if(isset($this->Cosmetico))
       {  
           return $this->Cosmetico->Empresa->getRazonSocial();
       } 
       else if(isset($this->Higiene))
       {  
           return $this->Higiene->Empresa->getRazonSocial();
       }
       else
           return $this->Reactivo->Empresa->getRazonSocial();
    }
    
    public function getLaboratorio()
    {
       if(isset($this->Medicamento))
       {
           $this->Medicamento->LaboratorioFabricante->getNombre();
       }
       else if(isset($this->DispositivoMedico))
       {  
           return $this->DispositivoMedico->LaboratorioFabricante->getNombre();
       } 
       else if(isset($this->Cosmetico))
       {  
           return $this->Cosmetico->LaboratorioFabricante->getNombre();
       } 
       else if(isset($this->Higiene))
       {  
           return $this->Higiene->LaboratorioFabricante->getNombre();
       }
       else
           return $this->Reactivo->LaboratorioFabricante->getNombre();
    }
    
}
