<?php

/**
 * ProductoUnimedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoUnimedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoUnimedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoUnimed');
    }
}