<?php

/**
 * ProductoWebTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoWebTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoWebTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoWeb');
    }
}