<?php

/**
 * ReactivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReactivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReactivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reactivo');
    }
}