<?php

/**
 * ReactivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReactivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReactivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reactivo');
    }
    
    public function selectReactivosDeEmpresa()
    {
        $user = sfContext::getInstance()->getUser();
        $empresa = $user->getAttribute('empresa');
        $q = Doctrine_Query::create()
                    ->from('Reactivo r')
                    ->where('r.empresa_id = ?', $empresa->getId())
                    ->orderBy('r.id ASC');
            
        return $q;
    }
}