<?php

/**
 * RegenteFarmaceutico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    anbeed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RegenteFarmaceutico extends BaseRegenteFarmaceutico
{
//    public function __toString() 
//    {
//        return $this->getMatriculaProfesional();
//        
//    }
    
    public function __toString()
    {
       return $this->getPersona()->getNombre(). " ".$this->getPersona()->getApPaterno(). " ".$this->getPersona()->getApMaterno() ;
    }
}
