<?php

/**
 * RegenteFarmaceuticoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegenteFarmaceuticoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegenteFarmaceuticoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegenteFarmaceutico');
    }
}