<?php

/**
 * SatisfaccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SatisfaccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SatisfaccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Satisfaccion');
    }
}