<?php

/**
 * ServiciosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiciosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiciosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Servicios');
    }
}