<?php

/**
 * TipoEtapaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoEtapaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoEtapaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoEtapa');
    }
}