<?php

/**
 * TipoProductoFormulario5Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoProductoFormulario5Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoProductoFormulario5Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoProductoFormulario5');
    }
}