<?php

/**
 * TipoCalificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoCalificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoCalificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoCalificacion');
    }
}