<?php

/**
 * TipoVentaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoVentaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoVentaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoVenta');
    }
}