<?php

/**
 * TipoTramiteFormulario27Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTramiteFormulario27Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTramiteFormulario27Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTramiteFormulario27');
    }
}