<?php

/**
 * TipoTramiteFormularioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTramiteFormularioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTramiteFormularioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTramiteFormulario');
    }
}