<?php

/**
 * TipoDespachoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoDespachoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoDespachoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoDespacho');
    }
}