# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        ANBEED S.R.L.
    #description:  symfony project
    keywords:     anbeed
    language:     en
    #robots:       index, follow

  stylesheets:    [settings.css, style.css, font-awesome.css, menu_web.css]

#  javascripts:    [jquery.js, custom.js, jquery.core.js, jquery.superfish.js, jquery.jcarousel.pack.js, jquery.easing.js, jquery.scripts.js, jquery.themepunch.plugins.min, jquery.themepunch.revolution.min]
  javascripts:    [jquery-1.7.1.min.js, custom.js, jquery.themepunch.plugins.min.js, jquery.themepunch.revolution.min.js]

  has_layout:     true
  layout:         layout
