# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        ANBEED S.R.L.
    #description:  symfony project
    keywords:     anbeed
    language:     en
    #robots:       index, follow

  stylesheets:    [style.css]

  javascripts:    [jquery.core.js, jquery.superfish.js, jquery.jcarousel.pack.js, jquery.easing.js, jquery.scripts.js]

  has_layout:     true
  layout:         layout
