generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Persona
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          persona_persona_usuario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        usuario:         {label: 'Datos de usuario'}
        ap_paterno:      {label: 'Ap. Paterno'}
        ap_materno:      {label: 'Ap. Materno'}
        cedula_expedido: {label: 'Cédula de identidad'}
        ci:              {label: 'Cédula de Identidad'}
        expedido:        {label: 'Expedido'}
        direccion:       {label: 'Dirección'}
        telefono:        {label: 'Teléfono'}
        celular:         {label: 'Celular'}
        fax:             {label: 'Fax'}
        casilla:         {label: 'Casilla'}
        email:           {label: 'Email'}
        nombre_ordenado: {label: 'Persona'}
        username:        {label: 'Usuario'}
      list:  
        table_method: selectUsuariosDisponibles
        title: Listado de Usuarios del sistema
        display: [username, nombre_ordenado, cedula_expedido]
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter:  
        display: [ap_paterno, ap_materno, nombre, ci]
      form:    ~
      edit:    
        title: Editar Usuario %%username%%
      new:     
        title: Registro de nuevo Usuario
        display:
          Datos de persona: [nombre, ap_paterno, ap_materno, ci, expedido, direccion, telefono, celular, fax, casilla, email, fecha_nacimiento, is_active, foto]
          Datos de usuario: [usuario]
