generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Persona
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          persona_persona_usuario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        usuario:          {label: 'Datos de usuario'}
        ap_paterno:       {label: 'Apellido Paterno'}
        ap_materno:       {label: 'Apellido Materno'}
        ap_casada:        {label: 'Apellido Casada'}
        cedula_expedido:  {label: 'Cédula de identidad'}
        ci:               {label: 'Cédula de Identidad'}
        expedido:         {label: 'Expedido'}
        direccion:        {label: 'Dirección'}
        telefono:         {label: 'Teléfono'}
        celular:          {label: 'Celular'}
        fax:              {label: 'Fax'}
        casilla:          {label: 'Casilla'}
        email:            {label: 'Email'}
        nombre_ordenado:  {label: 'Persona'}
        username:         {label: 'Usuario'}
        is_active:        {label: 'Activo?'}
        fecha_nacimiento: {label: 'Fecha de nacimiento'}
      list:  
        table_method: selectUsuariosDisponibles
        title: Listado de Usuarios del sistema
        display: [username, nombre_ordenado, cedula_expedido]
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter:  
        display: [ap_paterno, ap_materno, nombre, ci]
      form:
        display:
          Datos de persona: [nombre, ap_paterno, ap_materno, ap_casada, ci, expedido, direccion, telefono, celular, fax, casilla, email, fecha_nacimiento, is_active]
          Datos de usuario: [usuario]
      edit:    
        title: Editar Usuario %%username%%
      new:     
        title: Registro de nuevo Usuario
        
