generator:
  class: sfDoctrineGenerator
  param:
    model_class:           formulario706
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario706
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha:                    {label: Fecha, date_format: dd/MM/yyyy}
        tipo_tramite_formulario5: {label: Tipo de Trámite}
      list:
        title: Listado de Formularios 706
        table_method: selectForms706DeEmpresa
        display: [higiene, tipo_tramite_formulario, fecha, etapa]
        batch_actions:  {}
        actions:
          ir_portal:    {label: Volver al portal}
        object_actions:
          etapa: {label: Seguimiento, action: etapa}
          show:  {label: Información, action: show}
      filter:
        display: [higiene_id, tipo_tramite_formulario_id]
      form:    ~
      edit:    ~
      new:     ~
