generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Formulario706
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario706
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fields:  
        laboratorio: {label: 'Laboratorio Fabricante'}
        
      list:
        title: Desiciones 706 registrados
        display: [higiene, laboratorio, tipo_tramite_formulario]
        actions:
          ir_portal: {label: Volver al Portal}
        object_actions:
          edit: {label: Editar, action: editar}
      
      filter:
        display: [higiene_id, tipo_tramite_formulario_id]
      form:    ~
      edit:    ~
      new:     ~
