<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    public static function getUsuariosClientes()
    {
        
        $q = Doctrine_Query::create()
            ->from('sfGuardUser u')
            ->innerJoin('u.Empresa e') 
            ->orderBy('u.id ASC');
        
        return $q;
    }
    public static function getUsuariosPersonas()
    {
        
        $q = Doctrine_Query::create()
            ->from('sfGuardUser u')
            ->innerJoin('u.Persona p') 
            ->orderBy('u.id ASC');
        
        return $q;
    }
}