generator:
  class: sfDoctrineGenerator
  param:
    model_class:           IniciacionFormulario
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          iniciacion_formulario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        etapa_id:    {label: 'Producto'}
        descripcion: {label: 'Descripción'}
        observacion: {label: 'Observación'}
      list:
        title: Tramites iniciados
        table_method: selectEtapasDeEmpresa
        display: [tramite, descripcion, observacion]
        object_actions:
          producto: {label: Producto}
          _edit: ~
          _delete: ~
        batch_actions: {}
        actions:
          adm_empresa: {label: Volver a Empresa}
          _new: ~ 
      filter:
        display: [tramite]
      form:
        actions:
          _list: ~
          _save: ~
      edit:
        display: [empresa_id, tramite, descripcion, observacion, fecha_fin]
        title: Editar tramite %%tramite%%
      new:
        display: [empresa_id, tramite, descripcion, observacion, fecha_fin]
        title: Nuevo tramite %%tramite%%
