generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Formulario706
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario706
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fields:  
        laboratorio: {label: 'Laboratorio Fabricante'}
      list:
        title: Desiciones 706 registrados
        table_method: selectForms706DeHigiene
        display: [fecha, tipo_tramite_formulario, empresa, higiene]
        actions:
#          ir_empresa:   {label: Volver a empresa}
          ir_productos: {label: Volver a higiéne}
          new:          {label: Nuevo, action: nuevo}
        object_actions:
          imprimir: {label: Imprimir, action: exportPdf}
          etapa:    {label: Etapa}
          edit:     {label: Editar, action: editar}
      filter:
        display: [higiene_id, tipo_tramite_formulario_id]
      form:    ~
      edit:    ~
      new:     ~
