generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Formulario706
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario706
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        laboratorio: {label: 'Laboratorio Fabricante'}
        fecha: {label: 'Fecha', date_format: dd/MM/yyyy}
      list:
        title: Desiciones 706 registrados
        table_method: selectForms706DeHigiene
        display: [fecha, tipo_tramite_formulario, etapa]
        actions:
          ir_productos: {label: Volver a higiéne}
          ir_empresa:   {label: Volver a empresa}
          new:          {label: Nuevo, action: nuevo}
        object_actions:
          imprimir: {label: Imprimir, action: exportPdf}
          etapa:    {label: Etapa}
          edit:     {label: Editar, action: editar}
      filter:
        display: [tipo_tramite_formulario_id]
      form:    ~
      edit:    ~
      new:     ~
