generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrigenFormulario5
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          origen_formulario5
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Origenes
        display: [nombre]
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter:  
        display: [nombre]
      form:    
        display: [nombre]
      edit:    
        title: Editar Origen %%nombre%%
      new: 
        title: Registro Origenes
