generator:
  class: sfDoctrineGenerator
  param:
    model_class:           formulario516
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario516
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha:                   {label: Fecha, date_format: dd/MM/yyyy}
        tipo_tramite_formulario: {label: Tipo de Trámite}
        cosmetico:               {label: Cosmético}
      list:
        title: Listado de Formularios 516
        table_method: selectForms516DeEmpresa
        display: [cosmetico, tipo_tramite_formulario, laboratorio, etapa]
        batch_actions:  {}
        actions:
          ir_portal:    {label: Volver al portal}
        object_actions:
          etapa: {label: Seguimiento, action: etapa}
          show:  {label: Información, action: show}
      filter:
        display: [cosmetico_id, tipo_tramite_formulario_id]
      form:    ~
      edit:    ~
      new:     ~
