generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user_cliente_usuario
    with_doctrine_route:   true
    

    config:
      actions: ~
      fields:
        username:       {label: 'Usuario'}
        is_active:      {label: 'Activo?'}
        password:       {label: 'Contraseña'}
        password_again: {label: 'Repetir Contraseña'}
      list:    
        title:        Listado de Usuarios Clientes
        display:      [empresa,username, is_active, last_login]
        table_method: getUsuariosClientes
      filter:  
        display: [empresa_id,username, is_active, last_login]
      form:    
        class: ClienteUsuarioForm
        display: 
          Empresa: [empresa_id]
          Datos Usuario: [username, password, password_again]
          Permisos: [is_active]
      edit:
        title: Editando Usuario "%%username%%"
      new:
        title: Nuevo Usuario Cliente