generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CodigoProducto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          codigo_producto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        created_at:   {label: 'Creado'}
        nombre:       {label: 'C贸digo  Producto'}
      list:    
        title:   Listado C贸digo  Producto  
        display: [nombre, created_at]
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter: 
        display: [nombre]
      form:    ~
      edit:    
        title:   Editar C贸digo Producto %%nombre%%
      new:     
        title:   Registrar C贸digo Producto 