generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Formulario516
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario516
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        laboratorio: {label: 'Laboratorio Fabricante'}
      list:
        title:   Desiciones 516 Registrados
        table_method: selectForms516DeCosmetico
        display: [fecha, tipo_tramite_formulario, empresa,  laboratorio, cosmetico]
        actions:
          ir_empresa:   {label: Volver a Empresa}
          ir_productos: {label: Regresar a Cosméticos}
          new:  {label: Nuevo, action: nuevo}
        object_actions:
          edit: {label: Editar, action: editar}   
      filter:  
        display: [cosmetico_id, tipo_tramite_formulario_id]
      form:    ~
      edit:    ~
      new:     ~
