generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Formulario516
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulario516
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Desiciones 516 Registrados
        actions:
          ir_empresa: {label: Volver a Empresa}
          ir_productos: {label: Regresar a Cosméticos}
          new: {label: Nuevo, action: nuevo}
          
      filter:  
        display: [cosmetico_id, tipo_tramite_formulario_id]
      form:    ~
      edit:    ~
      new:     ~
