generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Ciudad
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ciudad
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        nombre: {label: 'Ciudad' }
      list:    
        title: Listado de Ciudades
        display: [pais, nombre, distrito]
        actions:
          ir_portal: {label: Volver al Portal}
          _new: ~
      filter:  
        display: [pais_id, nombre]
      form:    ~
      edit:    
        title: Editar la Ciudad de %%nombre%%
      new:     
        title: Registrar Ciudad
