generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GrupoHigiene
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          grupo_higiene
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  
        display: [nombre]
      form:    
        actions:
          _save: ~
          cerrar: 
      edit:    
        title: Editar Grupo Higiene %%nombre%%
      new:     
        title: Registro de Grupo Higiene