generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProductoWeb
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          producto_web
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        max_per_page: 16
      filter:  
        display: [categoria_id,linea_id, pais_id, nombre]
      form:    ~
      edit:    ~
      new:     ~
