generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Persona
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          persona_personalegal
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        ap_paterno:      {label: 'Ap. Paterno'}
        ap_materno:      {label: 'Ap. Materno'}
        ci:              {label: 'Cédula de Identidad'}
        expedido:        {label: 'Expedido'}
        direccion:       {label: 'Dirección'}
        telefono:        {label: 'Teléfono'}
        celular:         {label: 'Celular'}
        fax:             {label: 'Fax'}
        casilla:         {label: 'Casilla'}
        email:           {label: 'Email'}
        
      list:
        title: Personas Registradas
        display: [nombre, ap_paterno, ap_materno, cedula_expedido]
        batch_actions: {}
        object_actions:
          asignar_personalegal: {label: Asignar Persona, action: asignarPersonalegal, params: 'class=boton-asignar confirm=¿Asignar al Personal?'}
        actions:
          ir_empresa: {label: Volver a Empresa}
          _new: ~
      filter:
        display: [ci]
      form:
        display: 
          Datos de la Persona:  [nombre, ap_paterno, ap_materno, ci, expedido, direccion, telefono, celular, fax, casilla, email, fecha_nacimiento]
          Datos de Representante: [Nuevo Representante]
      edit:
        title: Editar Representante Legal %%nombre%%
        actions:
          ir_empresa:          {label: Volver a empresa}
          quitar_personalegal: {label: Quitar Persona Legal, params: 'class=boton-quitar confirm=¿Quitar Persona Legal?'}
          _save: ~
      new:
        title: Nuevo Representante Legal
        actions:
          _list: ~
          _save: ~
