generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Higiene
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          higiene
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        empresa_id:                {label: 'Empresa'}
        laboratorio_fabricante_id: {label: 'Laboratorio Fabricante'}
        grupo_higiene:             {label: 'Grupo Higiene'}
        marca:                     {label: 'Marca'}
        pais_id:                   {label: 'País de código NSO'}
        nombre:                    {label: 'Nombre del producto'}
        phd:                       {label: 'PHD'}
        pahp:                      {label: 'PAHP'}
        variedad:                  {label: 'Variedad'}
        codigo_nso:                {label: 'Código NSO'}
        vigencia_nso:              {label: 'Vigencia de código NSO'}
        expediente:                {label: 'Expediente'}
        
      list:
        title:   Productos de higiene registrados
        table_method: selectHigieneDeEmpresa
        display: [nombre, marca, laboratorio_fabricante, registro_sanitario]
        object_actions:
          _edit: ~
          ir_form706:   {label: Desicion 706}
#          ir_form7:     {label: Form 007}
          _edit: ~ 
        actions:
          adm_empresa: {label: Volver a Empresa}
          _new: ~ 
          
      filter:
        display: [nombre, marca, laboratorio_fabricante_id, registro_sanitario]
        
      form:
        display:
         Datos: [empresa_id, laboratorio_fabricante_id, nombre, variedades, presentacion, nombre_detalle, grupo_higiene, marca, codigo_nso, expediente, vigencia_nso, pais_id, registro_sanitario]
        actions:    
          _delete: ~
          _list: ~
          _save: ~
          
      edit:
        title: Editar producto higiénico %%nombre%%
        
      new:
        title: Registro de producto higiénico
