generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Satisfaccion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          satisfaccion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        servicio_id:     {label: Elija el servicio}
        calificacion_id: {label: Califique el servicio}
        comentario:      {label: Introduzca su comentario}
      list:    ~
      filter:  ~
      form:    
        display: [servicio_id, calificacion_id, comentario, empresa_id]
        actions: 
          ir_portal: {label: Volver al portal}
          _save: ~
      edit:    
        actions: 
          ir_portal: {label: Volver al portal}
          _save: ~
      new:     
        title: Califique el Servicio que desee
        actions: 
          ir_portal: {label: Volver al portal}
          _save: ~
