generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Ingrediente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ingrediente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        nombre: {label: Nombre}
      list:    ~
      filter:  
      form:    
        actions: 
          _save: ~ 
          _save_and_add: ~ 
      edit:    
        title: Editar Ingrediente %%nombre%%
      new:     
        title: Nuevo Ingrediente
