generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FormulaCc
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formula_cc
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        contenido:             {label: 'Contenido'} 
        ingrediente_id:        {label: 'Principio Activo'} 
        NuevoDetalleFormulaCc: {label: 'Excipientes'}
        DetalleFormulaCc:      {label: 'Excipientes Resgistrados:'}
        NuevoPrincipio:             {label: 'Principio Activo:'}
        Principio:             {label: 'Principio Activo Registrados:'}
      list:    
        title:   Fórmulas Cualicuantitativas Registradas
        display: [observaciones]
      filter:  ~
      form:  
        display:  
          Fórmula Cualicuantitativa:                                 [contenido]
          Nuevo Principio Activo:                                    [NuevoPrincipio]
          Principio Activo Registrados:                              [Principio]
          Nuevo Excipiente de la Fórmula Cualicuantitativa:          [NuevoDetalleFormulaCc]
          Excipientes de la Fórmula Cualicuantitativa Registrado(s): [DetalleFormulaCc]
        actions:
          ir_productos: {label: Regresar a Medicamentos}
          _delete: ~
          _save: ~
      edit:   
        title:   Editar Fórmula Cualicuantitativa
      new:     
        title:   Registro de Fórmula Cualicuantitativa
