generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Producto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          producto_prodmed
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        laboratorio_fabricante_id: {label: 'Laboratorio Fabricante'}
        nombre_generico:           {label: 'Nombre Genérico'}
        procedencia:               {label: 'Lugar de Procedencia'}
        registro_sanitario:        {label: 'Número de Registro Sanitario'}
        descripcion:               {label: 'Descripción'}
      list:    
         title:   Medicamentos Registrados
         display: [nombre_generico, laboratorio_fabricante_id, registro_sanitario]
         actions:
          adm_empresa: {label: Volver a Empresa}
          _new:     ~ 
      filter:  
        display:  [laboratorio_fabricante_id, nombre_generico, registro_sanitario]
      form:
        display:  
          Datos Generales del Producto:   [laboratorio_fabricante_id, nombre_generico, procedencia, registro_sanitario, descripcion]
          Datos Específicos del Producto: [Nuevo Medicamento]
        actions:    
          _list: ~
          _save: ~
          
      edit:    
        title: Editar Medicamento %%nombre_generico%%
      new:     
        title: Registro de Medicamentos