generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Cosmetico
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cosmetico
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fields: 
        laboratorio_fabricante_id: {label: 'Laboratorio Fabricante'}
        forma_cosmetica_id:        {label: Forma Cosmética}
        grupo_cosmetico_id:        {label: Grupo Cosmético}
        marca:                     {label: Marca}
        nombre:                    {label: Nombre del producto}
        codigo_nso:                {label: Código de identificación de la NSO}
        expediente:                {label: Número de Expediente}
        vigencia_nso:              {label: Vigencia del Código de identificación de la NSO}
        pais_id:                   {label: País que emitió el Código de identificación de la NSO}
        registro_sanitario:        {label: 'Nº de Registro Sanitario'}
        descripcion:               {label: 'Descripcion'}
      list:    
        title:   Cosmeticos Registrados
        table_method: selectCosmeticosDeEmpresa
        display: [nombre, marca, laboratorio_fabricante, registro_sanitario]
        object_actions:
          ir_form516:   {label: Desicion 516, action: irForm516}
#          ir_form7:     {label: Form 007, action: irForm7}
          _edit: ~ 
        actions:
          adm_empresa: {label: Volver a Empresa}
          _new:     ~ 
      filter:  
        display: [nombre, marca, laboratorio_fabricante_id, registro_sanitario]
      form:
        display:
          Datos Generales del Producto: [laboratorio_fabricante_id, nombre, forma_cosmetica_id, grupo_cosmetico_id, marca, codigo_nso, expediente, vigencia_nso, pais_id, registro_sanitario, descripcion]
        actions:    
          _delete: ~
          _list: ~
          _save: ~
      edit:    
        title: Editar Cosmético %%nombre%%
      new:     
        title: Registro de Cosméticos  
