generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Aval
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          aval
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
        display: [codigo, nombre_generico, concentracion]
      filter:  
        display: [codigo, nombre_generico]
      form:    ~
      edit:    ~
      new:     ~
