generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Persona
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          persona_personaregente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        ap_paterno:      {label: 'Ap. Paterno'}
        ap_materno:      {label: 'Ap. Materno'}
        cedula_expedido: {label: 'Cédula de identidad'}
        ci:              {label: 'Cedula de Identidad'}
        expedido:        {label: 'Expedido'}
        direccion:       {label: 'Dirección'}
        telefono:        {label: 'Teléfono'}
        celular:         {label: 'Celular'}
        fax:             {label: 'Fax'}
        casilla:         {label: 'Casilla'}
        email:           {label: 'Email'}
        nombre_ordenado: {label: 'Persona'}
        
      list:
        title: Listado de Regentes Farmaceuticos disponibles
        table_method:   selectPersonasDisponibles
        display: [nombre_ordenado, cedula_expedido, telefono]
        object_actions:
          asignar_personaregente: {label: Asignar Persona, action: asignarPersonaregente, params: 'class=boton-asignar confirm=¿Asignar al Personal?'}
        actions:
          ir_empresa: {label: Volver a Empresa}
          _new: ~
      filter:
        display: [ap_paterno, ci]
      form:
        display: 
          Datos de la Persona:  [nombre, ap_paterno, ap_materno, ci, expedido, direccion, telefono, celular, fax, casilla, email, fecha_nacimiento]
          Personal Responsable: [Nuevo Regente]
      edit:
        title: Editar Regente Farmaceutico %%nombre%%
        actions:
          ir_empresa:            {label: Volver a empresa}
          quitar_personaregente: {label: Quitar Regente Farmaceútico, params: 'class=boton-quitar confirm=¿Quitar Regente Farmaceútico?'}
          _save: ~
      new:
        title: Nuevo Regente Farmaceutico
        actions:
          _list: ~
          _save: ~