generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Pais
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pais
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: 
        title: Paises Registrados
        display: [nombre]
        actions:
          ir_portal: {label: Ir a Portal}
          _new: ~
      filter:  
        display: [nombre]
      form:    
        display: [nombre, bandera]
      edit:
        title: Editar Pais %%nombre%%
      new:     
        title: Registro de Paises
