generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Marca
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          marca
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        nombre: {label: Nombre}
      list:    ~
      filter:  
      form:    
        actions:
          _save: ~
          cerrar: 
      edit:    
        title: Editar Marca %%nombre%%
      new:     
        title: Registro de Marca